### ISSUE TITLE
Add app drawer/favorites animations

### ISSUE THREAD

**Issue by drewski-00h** [falzonv/discreet-launcher#101]
As the app drawer/favorites drawer are now, they're either all the way open, or all the way closed.  Would it be possible to add some nice animations to drag the drawers up, following the users finger?  I can clarify is this idea isn't clear.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!

However, I do not plan to implement animations for the two following reasons:
- One of the goals I try to keep with this launcher is to provide instant access to favorites or app drawer with one gesture (which can even be very small, the "trigger limit" for the swipe is quite low).
  - Adding an animation (ex: roll or slide) would automatically delay the access to apps by the length of the animation. Even if it only adds 100-200ms, this delay is something that always frustrated me in other launchers I used before.
- It would also add a lot of complexity in the code because currently there are no animations at all: the swipes just show/hide the panels (like simple clicks would do, but here swipes are more flexible and avoid accidental open/close).
  - Adding animations would require to track the finger position during the swipe and compute the related panel part to display (probably even more complicated, because the swipe can be any length and we don't know when it will end), to manage multi-touch if the user (long-)clicks an app during the animation, to manage swipes back-and-forth, etc.

Sorry I will close this ticket, but feel free to add comments if needed or wished.

Best regards.
