### ISSUE TITLE
Scrolling sections

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#105]
Help has a top section "Help" that isn't found in 

"Changelog" (where it is an indication of how @name works which can also be removed).
If the colouring does anything, the lines aren't needed, which is what makes

Settings and help - barely scroll for me.

Really the problem is the lineshift between the section and the content. Seems like an Android thing to do.

**Comment by falzonv** [comment]
Hello,

I am not sure to understand you request.
=> Do you mean that the lines separating the sections in the Help should be removed?

Currently the Help and Changelog are not working the same way internally:

- The Help is built using the Preference framework, the same used for all the settings (look at [res/xml/settings_help.xml](https://github.com/falzonv/discreet-launcher/blob/main/app/src/main/res/xml/settings_help.xml), it should clarify how it is built and how the help strings are loaded)
  - Separating lines are automatically added between PreferenceCategory elements
  - When navigating in the Help, since it is part of the settings, the title stays the same than in the previous screen ("Settings and help"). This is why I added another "Help" on top to act as the title.
- Initially the Changelog was built in the same way than the Help, using the Preference framework (and there was also a "Changelog" title on top, like today with the Help).
  - When I decided to reuse the fastlane release notes, it was not possible anymore to use the Preference framework because the content needed to be loaded dynamically (loading all the files from the changelog folder in "assets").
  - Therefore I converted the Changelog to a real Android activity.

Best regards.

**Comment by comradekingu** [comment]
Thank you for the explanation. :)
This is the current view:
![bilde](https://user-images.githubusercontent.com/13802408/129627658-649f831c-561f-4434-a745-13960f40990e.png)
It would do the same thing without all the fields in red.
![bilde](https://user-images.githubusercontent.com/13802408/129628253-eff2e86d-512a-4280-99c9-7ee937b6c228.png)

**Comment by falzonv** [comment]
Ok, now this is clear.
It will require to refactor the Help into a real Android activity, I will have a look but there should not be any issue to do it.

*Remark: I will be away from Internet and GitHub for a couple of weeks.*

**Comment by falzonv** [comment]
This will be solved in the next release, as discussed in the menu ticket.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been implemented in new release v5.0.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Since v5.0.0 is now available on F-Droid, I will close this ticket.
Feel free to add comments if needed or wished.
