### ISSUE TITLE
Gesture navigation doesn't work on Android 10

### ISSUE THREAD

**Issue by JM480** [falzonv/discreet-launcher#109]
The gesture navigation that was added in Android 10 can't be used with this launcher, but it works with LineageOS 18.1 (Android 11). I think this bug only affects Android 10.

**Comment by falzonv** [comment]
Hello,

Thank you for the bug report!

It may look as a stupid question but could you precise what the Android 10 gesture navigation is supposed to do? *(my phone is on Android 8 so I am not familiar with all the last features)*
Do you mean that the up/down swipes are not working?

*Remark: I will be away from Internet and GitHub for a couple of weeks and will probably not see your answer before my return.*

Best regards.

**Comment by JM480** [comment]
The gesture navigation uses gestures from the bottom of the screen to swipe up to go to the home screen, swiping up and holding for the recents menu, swiping left and right from the bottom to switch apps and swiping from the edges of the screen to go back. The gesture navigation option can't be selected on my tablet because the launcher doesn't support it.

**Comment by falzonv** [comment]
Ok, thank you for the explanation (and sorry for the late answer, as explained I was away last weeks).

My assumption is then that the gestures are catched as swipes by Discreet Launcher (to open/close favorites and drawer) but it is strange that this bug happens only in Android 10 and not 11.
I will have a look, maybe it could be solved by making DL ignore swipes in a certain area at the bottom of the screen...

**Comment by falzonv** [comment]
Hello @JM480,

After further reading, I now understand why it works with Android 11 and not with Android 10.
Unfortunately this is not something I will be able to solve on my side, really sorry for that :-/

Explanation: with Android 10 firsts versions, gesture navigation is disabled for custom launchers!
It shows a misleading message blaming the launcher, but in fact this is a system restriction. In the most recent Android 10 versions, Google removed this limitation which is why it now works with Android 11.

Here are two interesting articles about this bug below, from which I highlighted the most relevant parts.

I will close the ticket but feel free to add comments if needed or wished.

Best regards.

---

https://help.niagaralauncher.app/article/7-gesture-navigation

> The reality is, **Android disabled gesture navigation for third-party launchers on the first builds on Android 10 because the developer team struggled with lots of bugs**:
>
> > Custom launchers are another area where we’ve heard feedback and we’re continuing to work on issues, particularly with stability and Recents. **Starting in Beta 6, we’ll switch users to 3-button navigation when they are using a custom launcher by default.** We’ll address the remaining issues in a post-launch update allowing all users to switch to gestural navigation. [[Source](https://android-developers.googleblog.com/2019/07/android-q-beta-5-update.html)].
>
> **In December 2019, Google released a patch that allows gesture navigation to work with third-party launchers**. Your phone manufacturer needs to integrate this patch into their codebase.

---

https://android.gadgethacks.com/how-to/android-10-gesture-controls-grayed-out-heres-fix-0200786/

> The problem is, Google doesn't want to give extra permissions to any old third-party launcher, or any third-party app for that matter. This integration has caused **bugs with third-party launchers since Android 10's first beta release, so as of beta 5 and 6, Google decided to simply disable the gestures if you have a custom launcher installed**. They've said they'll fix this problem at some point in the coming months, but until then, there's an easy fix.

The fix(?) mentioned in the article is to uninstall the custom launcher and use the Android default launcher instead.
Not very helpful...
