### ISSUE TITLE
"Always show favorites" not working if menu button hidden (v4.7.0)

### ISSUE THREAD

**Issue by tuch96** [falzonv/discreet-launcher#113]
Hi Vincent,

with the current version, I can no longer permanently activate the "Always show favorites" function. If I activate the function in the settings and leave the settings again, the function is deactivated.

**Comment by jlamoure** [comment]
tuch96, recommend you change title to directly identify the issue, e.g. "Always show favorites option no longer works"

In my case, it shows toast "Reinstating the app drawer to keep menu access." The "no app drawer" option also shows this toast when enabled, however, when "no menu button" is disabled, neither option show this toast. In fact in testing while writing this up I can say this is a workaround and my favorites now are always shown. I will not test the no app drawer option without the settings button visible as I'm not sure how I'd access the settings.

My app is also v4.7.0.

Love the app and categorization features. Thanks

**Comment by tuch96** [comment]
@jlamoure , thanks for your feedback!

**Comment by falzonv** [comment]
Hello @tuch96,

Oups, sorry for the issue! (in addition, I was away the last weeks and see your bug report only now)

When removing the favorites limit (as per ticket #100), I added some checks to make sure there is always a way to access the launcher menu but I must have missed something.

As suggested by @jlamoure, the current workaround is to enable the menu button (another one is to rollback to v4.6.1).
I will have a look on what is going wrong with the "no menu button" case...

Best regards.

---

> **jlamoure:** I will not test the no app drawer option without the settings button visible as I'm not sure how I'd access the settings.

If you have the Discreet Launcher icon in favorites (either directly or from a folder) or the Search icon in favorites, you will be able to access the menu from there. Otherwise, the "no app drawer" setting should be automatically disabled.

**Comment by tuch96** [comment]
Hey @falzonv ,

welcome back :-)! I have made a rollback to v4.6.1 and wait for a newer version.

Cheers
Marc

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been solved in new release v5.0.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Since v5.0.0 is now available on F-Droid, I will close this ticket.
