### ISSUE TITLE
Compact Layout Full View

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#128]
![Screenshot_2021-09-21-09-00-19](https://user-images.githubusercontent.com/67331785/134171385-ce798070-87dc-46bd-8b3f-62e814267a80.png)

![Screenshot_2021-09-21-08-58-39](https://user-images.githubusercontent.com/67331785/134171403-d75892b2-94b7-4375-94e1-b6cd67d75b5b.png)

**The second picture after swipe show full (compact grid_view with label) and favorites with menu settings (no label).** 
- icons waste memory so while pick favorite just jump the app to favorites, no need duplicate. (or gridview or favorites so it keep low memory)
- the layout grid_view have a limited area view, so scroll is needed, also favorites.

**i know, you don't like me trying change the app :)**

**Comment by xi7** [comment]
![Screenshot_2021-09-22-22-58-48](https://user-images.githubusercontent.com/67331785/134500235-a4295156-2b84-459c-a721-ca11f8480689.png)

landscape view

**Comment by falzonv** [comment]
Hello,

After a few tests, splitting apps between favorites and drawer adds a lot of complexity everywhere in the launcher because there are many places where the full list is needed for display or proper internal operation (ex: search, folders organizer, hidden apps, new swipe gestures, etc.). It would surely introduce many bugs and instabilities.
Thank you for the suggestion but I will not implement it.

I also do not plan to introduce new layout(s) in the app, sorry.

---

Regarding the reduction of the number of icons in memory, we saw in ticket #90 that Discreet Launcher used only 4% of your RAM (screenshot below, 21.07MB out of 526.53MB represents 4%).
If this is really a problem for you, I think the only solution to significantly reduce memory usage will be to use a text-based launcher, such as [Light Android Launcher](https://f-droid.org/pt_BR/packages/com.github.postapczuk.lalauncher/) that you showed me few months ago.

Best regards.

<img src="https://user-images.githubusercontent.com/67331785/125288746-dcd86980-e2f4-11eb-8a46-43710e79ea7b.png" width="40%"/>

**Comment by xi7** [comment]
what the compact view is ? favorites with drawer without replicate icons !
and if u just put a simple code (drawer compare favorites and list on top)

![Screenshot_2021-10-08-07-40-37](https://user-images.githubusercontent.com/67331785/136543775-6304ebdb-fbaa-42c5-a2b7-9a1aa78368a8.png)

this the final result **compact view**
(less icons, low memory, less swipe)
