### ISSUE TITLE
Avoid moving clock between views

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#131]
Pulling down favorites (or main apps) creates a focus shift when the clock moves.
I would expect it to stay in place.

I think either running the favorites below the clock (when top), or doing it behind the apps is better.
Probably the latter would work nicely for both "top" "middle" and "bottom".

Edit: Did I just falsely remember options for placement? In the standby screen it is sort of in the middle and has a bit thicker font.
Maybe trying to replicate it is the most elegant way?

**Comment by falzonv** [comment]
Hello,

My initial idea was to keep the clock visible even when the favorites panel is opened, but maybe this is not really necessary.

This is a bit difficult for me to assess because I do not use the clock on my regular phone, only on emulators (as a matter of fact, from all the settings added since v1.0.0, the only one I use is the "forced portrait-mode" ; not much customization :joy:).

If we decide to not make the clock move, I would prefer the second option (clock shown behind the apps) because, as you pointed out, it would also work with the clock placement options which will be added in v5.1.0.

Currently, these options "top", "middle" and "bottom" are based on the space between the favorites panel and the other side of the screen (bottom in classic interface, top in reversed interface). This space is different whether or not the panel is closed, which makes the clock moves accordingly in most cases.
=> The solution would involve to make this placement unrelated to the favorites panel.

Best regards.

**Comment by falzonv** [comment]
Ok, I found a way to make it work and it should be fixed in v5.1.0.

**Comment by falzonv** [comment]
Since v5.1.0 is now available on F-Droid, I will close this ticket.
Feel free to add comments if needed or wished.
