### ISSUE TITLE
hide's concept

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#133]
![Screenshot_2021-09-27-08-26-58](https://user-images.githubusercontent.com/67331785/134900853-4cdd4759-9a2c-4522-8a4a-c456cd68dba5.png)

it's not because it's hidden than will stop working the app.

**Comment by falzonv** [comment]
Hello,

I confirm that, for internal reasons, hidden apps cannot be selected for swipe gestures.
So if any app was selected and then hidden (or uninstalled), it will display the popup message like on your screenshot.

The workaround is easy with two options: un-hide the app, or select another app (or none) for the swipe gesture.

Maybe when the selected app is not found (either because uninstalled or hidden), I should reset the related swipe gesture to "none" in order to not display the message again, I will have a look...

Best regards.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/135250302-b6b39083-b00b-4649-832a-f4b31f5efc1b.mp4

another bug with always show favotires.

about swipe gesture it need open any app even if hide.

**Comment by falzonv** [comment]
> another bug with always show favorites.

Nice catch thank you, the fix will be integrated in next release v5.1.1.

> about swipe gesture it need open any app even if hide.

As explained above this will not be done.
Hiddens apps are removed from everywhere in the launcher, even from the selections menus (this is because on some phones there are bloatware apps that cannot even be disabled, that way they can be hidden). By the way, icons from hidden apps are also removed from memory.
If an hidden app needs to be accessed (by click, swipe, search or whatever), then it should be un-hidden first.
