### ISSUE TITLE
Option for app names color and text clock shadow color

### ISSUE THREAD

**Issue by janTaja** [falzonv/discreet-launcher#142]
I haven’t found a way to change the color of app names and right now it’s not very usable with light background. It would be nice to have an option to change the color and also to disable the clock shadow

![Screenshot_20211018-132249_Discreet Launcher.jpg](https://user-images.githubusercontent.com/53832230/137713843-2f0fe485-a0e3-4413-8175-e9a665fbca5c.jpg)

**Comment by falzonv** [comment]
@janTaja:
Good news, I am able to make the 3 settings work!
*(app names color / text clock shadow color / dark status bar icons ; last one works only with Android 6+)*

Still have several tests to finalize, all translations to update, etc. and then it should be released rather soon :-)

@xi7:
> possible add appearance icons with bar color ?

This will not be implemented, customize app icons further than selecting a pack is out of the scope of Discreet Launcher.

**Comment by xi7** [comment]
> @xi7:
> 
> > possible add appearance icons with bar color ?
> 
> This will not be implemented, customize app icons further than selecting a pack is out of the scope of Discreet Launcher.

the solution presented is better than choose icon pack, with 100% hit on the icons, while choose pack with lucky doesn't reach 30%

**Comment by falzonv** [comment]
@xi7: ok now I see your point, indeed this can be useful.
I will have a look (created ticket #149 for follow-up).

**Comment by falzonv** [comment]
Hello @janTaja,

I am pleased to inform you that the 3 settings have been implemented in new release v5.2.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by janTaja** [comment]
Hi, thank you a lot for this @falzonv! I’m moving to Discreet launcher now :)

Trying out the new version and I’ve noticed that the number of apps in a folder stays white, I think it should be the same color as app names?
![Screenshot_20211113-135939_Discreet Launcher.jpg](https://user-images.githubusercontent.com/53832230/141624667-4c455237-7c47-430d-8e65-353cb60b3ca7.jpg)

**Comment by falzonv** [comment]
Hello @janTaja,

Cool, I am glad you like it! :-)

> I’ve noticed that the number of apps in a folder stays white

=> Oh you are right, I missed that one!
I will fix it in the next release, thank you for the report.

Seeing your screenshot, I now wonder which color would be the best for the number of apps in the folder:

| Same than folder icon? | Or same than folder name? |
| ------------- | ------------- |
| ![2021-11-15_folder_icon_color1](https://user-images.githubusercontent.com/4698531/141768905-5f3d1c3d-0af2-4aa6-b006-055a5108ab13.png) | ![2021-11-15_folder_icon_color2](https://user-images.githubusercontent.com/4698531/141768908-0dded686-4b46-46a7-947f-664ddd983e9a.png) |

*(Note: the "5" looks pixelated because I used a photo editor and "Fill color" to make these quick examples. Within Android there is an anti-alias drawing option so it would not look pixelated. The idea here was just to show both color arrangements.)*

=> **Which one do you prefer?**

Another thing to consider:
To save system resources, folder icons are (re)created only when the app list is created/refreshed.
So in the second case, the color would *not* be updated right after the "app names color" setting change.
It would be updated only the next time the app list is refreshed because the number of apps is part of the folder icon (this is not a dynamic text like the app name, it is a text drawn inside the icon at its creation).

For this reason, **I would tend to prefer the first option** (same color than folder icon). That way, the number of apps color will always be updated at the same time than the folder icon color (in fact it would depend on the same setting).

Best regards.

**Comment by janTaja** [comment]
Now that I see both options, I think the first one looks better, go with it :)

**Comment by falzonv** [comment]
Hello,

Thank you for your feedback!

I implemented the fix in new release v5.2.1 :-)
This ticket will stay opened until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by falzonv** [comment]
Since v5.2.1 is now available on F-Droid, I close this ticket ;-)
