### ISSUE TITLE
shake drawer 

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#143]
https://user-images.githubusercontent.com/67331785/138686092-6d59e4d9-12bd-49f6-a3ad-4e8f94cbde7b.mp4

easier than click notifications ^_^

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/143877974-030a53c4-469a-4aff-8700-4904cd7e73f6.mp4

by sensor , both no need permission android.

**Comment by xi7** [comment]
after long test with sensor and shaking app not need be implemented.

**Comment by falzonv** [comment]
Hello,

Ok, thank you for the tests and feedback.
Since our first exchange I didn't had time to start working on this ticket to be honest, so no problem to close it.

Just for info, what was wrong with sensor or shake?
Is it that, past first discovery, the option is never used in real life?

Best regards.

**Comment by xi7** [comment]
shaking:
can be activated in any movement.

proximity sensor:
battery drain fast because is always on.

**Comment by xi7** [comment]
the best idea is you overlay the search and we can use Key Mapper app.

**Comment by falzonv** [comment]
Hello,

Ok, thank you for the feedback.

Key Mapper is interesting, I didn't know we had this kind of apps on F-Droid :-)
Good news, with a code modification, we can allow Key Mapper to launch the "ActivityNotification" which display the favorites over another app!

Since the next release should happen only in February, you will find below an APK with the modification applied if you want to test:
https://file.re/2022/01/26/discreet-launcherv541exportactivitynotification/

After applying the configuration below, it works fine for me.
I hope this will work for you as well!

*Note: as we saw in another ticket, calling the Search directly doesn't work properly.
But you can add the Search in the favorites and it will be almost the same.*

---

Here is how to add the action in Key Mapper :
- Click the button "Add action"
- Browse up to the "INTENT" tab
- Enter a description, something like "Discreet Launcher Favorites" for example
- Select the type "Activity"
- Go down and click the button "Choose Activity"
- In the long list which appears, navigate up to Discreet Launcher and select the activity "com.vincent_falzon.discreetlauncher.notification.**ActivityNotification**"
- This will auto-fill the fields "Package" and "Class" above
- Go a bit up and fill 469762048 in the field "Flags" (more details about the reason for this below)
- Click the button "Done" and continue the Key Mapper setup as you wish

**Reason for the 469762048:**
If you remember at the beginning with the notification, we had an issue where it was coming back to the home screen.
This was solved by adding the combination of the flags "Intent.FLAG_ACTIVITY_NEW_TASK", "Intent.FLAG_ACTIVITY_MULTIPLE_TASK" and "Intent.FLAG_ACTIVITY_CLEAR_TOP" to the intent used to call "ActivityNotification".
When Key Mapper calls "ActivityNotification", he has to set these flags as well or the same issue (go back to the home screen) will appear.
Each of these flags has a value (respectively 268435456, 134217728 and 67108864) and to combinate them we need to perform an "OR" operation at bit level.
The result of this computation is 469762048.

---

Best regards.

**Comment by xi7** [comment]
working here, but open notification without overlay. (open normally but back to home)

try add the 'ActivityNotification' directly to shortcut list option.

**Comment by falzonv** [comment]
Perfect, thank you for the test!

Good idea for the shortcut list, I tried to do it in this version:
https://file.re/2022/01/26/discreet-launcherv541shortcutfavorites/

No weird number to enter this time, it is already included in the shortcut code :-)

**Comment by xi7** [comment]
great job, the service overlay is very nice

**Comment by falzonv** [comment]
Thank you :-)
