### ISSUE TITLE
Feature idea - centered favourites

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#151]
Favorites are meant to be the most accesible, but since they are the topmost entries
it becomes difficult to reach them with phone sizes getting bigger.

If favourites populated from the bottom it would be easier.
The spanner could be on top of that menu.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but there is already the "Reversed interface" option that use a layout displaying the favorites panel at the bottom of the screen (see "Operation > Reversed interface" in the settings).
I do not plan to implement a third layout where favorites would be in the center (would add a lot of internal complexity).

*About the phone sizes getting bigger, this is also something I observe but I don't get why constructors are doing this.
Now it starts to become difficult to find recent phones with size lower than 5.2" (which is already not really small).
When a phone cannot even fit in a trouser pocket, it is not really "mobile" anymore...*

Best regards.

**Comment by comradekingu** [comment]
I was thinking just two modes, where the favourites look like they do in "reversed", in the normal view.
I am thinking the thumb works like a windsheild-wiper, and the topmost part of the screen is harder to get to.

**Comment by falzonv** [comment]
> where the favourites look like they do in "reversed", in the normal view.

Probably we can improve the reversed view as you suggested in other tickets, but I do not plan to change the normal view.

I use it since 2019 (app creation, although it was published only in 2021) and never faced any significant issue with it. My phone screen size is 5.2" which is not really small (it is already more than twice my wallet).

Trying to pay a bit more attention on how I use my phone, I notice that I often use the thumb to open the favorites/drawer and the finger pointer of the other hand to launch the displayed apps.
When I need to use the phone with only one hand, I usually grab it so that the thumb is around the middle of the screen, which allows to reach most of the screen with only the thumb. Of course it also depends on the usage: if I want to use the keyboard with one hand I will grab the phone to place the thumb around the bottom, and if I want to change quick settings in the notification panel I will grab the phone to place the thumb around the top.

Never really thought about my phone handling before to be honest, interesting observations :-)
