### ISSUE TITLE
Feature idea - Icons for selecting favourites

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#152]
It would be easier to sort and select favourites if icons were shown next to the app names.

**Comment by falzonv** [comment]
Hello,

It should be possible for the sorting interface, I will have a look.

For the select dialog I prefer to keep it simple (using the Android default check boxes dialog) so this will not be done.
However, since v5.2.0 it is now possible to add/remove favorites directly from the favorites panel / app drawer, which offers a quite convenient alternative.

Best regards.

**Comment by falzonv** [comment]
Hello,

This has been implemented in new release v5.3.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by falzonv** [comment]
Since a couple of days v5.3.0 is now available on F-Droid so I will close this ticket.
Feel free to add comments if needed or wished.
