### ISSUE TITLE
Enable Seedvault encrypted backups

### ISSUE THREAD

**Issue by PandaCoderPL** [falzonv/discreet-launcher#157]
In my opinion it would be good idea to let users backup Discreet Launcher application using [Seedvault](https://github.com/seedvault-app/seedvault). [Here](https://github.com/grote/Transportr/commit/4dc38f429f75909a088d8bd8a5b3b5ddd8030f71) you can see example of how such backup option could be implemented in privacy-respecting way. More details about it [here](https://github.com/seedvault-app/seedvault/wiki/FAQ#why-do-some-apps-not-allow-to-get-backed-up). Thank you in advance.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion and links!
After looking into these however, I decided to not change the current implementation.

Here is why:

As correctly assumed in the Seedvault FAQ, the reason I set `android:allowBackup="false"` is for privacy, to prevent any data to be transmitted from the launcher towards Google servers.

Reading the FAQ answer, I came across the link https://security.googleblog.com/2018/10/google-and-android-have-your-back-by.html which tells more about the backup encryption.
It works only starting with Android 9 and rely on the user PIN/pattern/password.
There is a limit to the number of attempts for access but many users have very weak authentication (the famous "1234" and "0000", predictable lock patterns https://www.androidauthority.com/lock-pattern-predictable-636267/, etc.) so it is difficult to know the real strength of this encryption. Apparently a security audit was published, but the links are dead...

All of this is a real surprise to me because I always assumed the backups towards Google were already safely encrypted (disabling the backup was not about encryption or not, but to not store any data on Google servers).
With this article I discovered that this safety is debatable, and that before Android 9 there is no encryption at all!

Sorry, I will not implement this.

Best regards.
