### ISSUE TITLE
Make folder names bigger

### ISSUE THREAD

**Issue by RichFrogg** [falzonv/discreet-launcher#160]
Be able to adjust the size or make font size a little bigger on folder names.

**Comment by RichFrogg** [comment]
Or maybe make it bolder.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!
Setting the folder names in bold is a good idea and keep things simple, I will have a look.

Best regards.

**Comment by falzonv** [comment]
Hello Richard,

Finally got some time to test both options (see screenshots below), but I prefer the current implementation.

The bold option looks fine but it messes with the visual feedback as both are touching the bold attribute. Solving this adds more code complexity than I thought to parts that I want to keep simple and reactive.

With bigger font size, it feels a bit like a glitch and probably soon after implementing this I would have tickets asking if I made a typo because font sizes are different...

Sorry this is not something that I will implement.
However, another way which already exists and could make folders more visible (depending on your wallpaper) is to adjust the color of folder icons. You can do this by clicking the folder icons in the folders management window (access via "Folders" menu entry, or by clicking the title of an opened folder).

Best regards.

| Current | Bold names | Bigger font size |
| --- | --- | --- |
| <img src="https://user-images.githubusercontent.com/4698531/146532175-2b2a424a-a9fb-4e46-ad62-d729545eb1af.jpg"/> | <img src="https://user-images.githubusercontent.com/4698531/146532177-ef6d3b7e-f837-46a1-b2fe-e0b315f68ee0.jpg"/> | <img src="https://user-images.githubusercontent.com/4698531/146532178-6e7e5474-8650-4a92-8660-d0e4797bfdd0.jpg"/> |

**Comment by RichFrogg** [comment]
Thanks Vincent!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
