### ISSUE TITLE
Choose custom icon for individual app

### ISSUE THREAD

**Issue by privatebeach** [falzonv/discreet-launcher#162]
I love your launcher! Unfortunately, the icon pack I use doesn't support all the apps I use (see pic). 

It would be nice for me to be able to long-select the app and change its icon to another in an installed icon pack, or a custom icon file stored on the phone.

Thank you again for a great, clean launcher!
![Screenshot_20211213-021226_Discreet Launcher](https://user-images.githubusercontent.com/89283975/145768268-f6edaad4-3b23-48c0-988a-3a8f89e35b1a.jpg)

**Comment by falzonv** [comment]
Hello,

Thank you for your feedback, I am glad you like Discreet Launcher!

In #112 and #137, I said that customize app icons further than selecting a pack is out of the scope of Discreet Launcher (for history, icon packs were not even supported before v1.1.0 ; it was quite a challenge to implement).

Now, the combination of tickets #130 and #149 (both planned for next release) will offer more settings to play with regarding app icons (I made the color filter from #149 apply only on default icons, so that it can be use in complement of icon packs).
Selecting an icon manually for each app is still something that I do not plan to implement as it would add a lot of code complexity, potential bugs and maintenance troubles.

Otherwise, the best way to fix missing icons is to contact the icon pack maintainer to ask for their inclusion. That way, these new icons are also displayed in all other launchers for people having these apps.

Best regards.
