### ISSUE TITLE
add shuffling wallpapers

### ISSUE THREAD

**Issue by dgcampea** [falzonv/discreet-launcher#17]
## Feature request:

Simple wallpaper shuffling configured via settings:
Possible menu representation:
- Shuffling wallpapers
  - Enable/Disable (toggle)
  - Directory to wallpapers (select directory)
  - Duration between shuffles (input time in second or minutes:seconds)
  - _(optional) Shuffle order (by alphabetic-order/random)_

## How it should work
Launcher only retrieves images from configured directory and applies them as wallpaper.
Images being properly cropped or formatted is left to the user.

**Comment by falzonv** [comment]
Hello,

Thank you for your suggestion, it is quite clear and well described!

I am a bit worried that it would require two additional permissions however:
- SET_WALLPAPER which is quite logic, no major issue for this one
*(currently the application do not need this one as it does not manage the wallpaper at all ; it can be defined with option "Set as" in most Gallery applications and the launcher just uses a fully transparent background to show the wallpaper)*
- **READ_EXTERNAL_STORAGE** to access files outside the application specific directory (in this case it would be to load the images used as wallpaper, probably from the gallery) => for me, **this one is a blocking point**.

Maybe there are some folders where the user could write and the application could read without any permission required but I am not sure to be honest (otherwise the permission would probably not exist in the first place).

Will think about it...

Best regards.

**Comment by falzonv** [comment]
Hello,

Working on the export/import feature from v2.4.0 was the occasion to learn more about storage access:
- No user files or directories can be accessed directly without the READ_EXTERNAL_STORAGE permission
- However, 2 things are possible without needing any permissions:
  - Read one file explicitly selected by the user using the file picker
  - Write one file to a location and with a name both explicitly specified by the user using the file picker *(not needed in our case, I mention it only for completeness)*

Therefore, the only solution I see which does not require this READ_EXTERNAL_STORAGE permission would be that the user imports manually the wallpapers in the application:
- An interface (maybe in "Export / Import" section) would allow to import wallpapers (or remove previously imported ones)
- For each wallpaper the user would have to select the image file that the launcher should copy in its internal files to be able to display it later as wallpaper

Of course, all of this is quite less flexible than the directory selection you were proposing...
What do you think about it?

Best regards.

**Comment by dgcampea** [comment]
Hi,
The approach you propose "works" but there are some practicality issues with it for importing large amounts of pictures is impractical (there's also duplication issues). For a tiny library it works though.

About the file access permission, if the issue is having the app with default filesystem permissions, I think there are some applications that only request it when required (if the wallpaper feature isn't ever enabled, it stays without filesystem access permission)

**Comment by falzonv** [comment]
Hello,

Yes, after reading your message and further thinking, I agree that the file picker is not a good solution and would require too many operations from the user. Duplicates could be managed but there are other things, for example the user may want to make several tries to crop an image exactly as (s)he wants and this would require to import/remove each time. Even for a small library it can quickly become irritating to reproduce for the Xth time the import operation.
This was an idea from when I finalized the export/import feature but it would not work on long term, even to maintain...

---

You are right about the way the file access permission is accepted by the user, the popup proposing to accept/decline would be displayed only when needed, and even not at all if the user never goes in this section.

However, the possibility to use that permission still needs to be declared in the application manifest so it will be listed in the "Permissions" section of F-Droid, shown in red by applications such as AppManager, etc.
Unfortunately the file access permission cannot be targeted to "pictures only" for example, it is either "access to all user files on the system" or "access to nothing except using the manual file picker". Privacy is probably why this permission has been flagged with the protection level "dangerous" in Android documentation.

Currently, the only permission required by Discreet Launcher is "android.permission.QUERY_ALL_PACKAGES" and users can understand it because this is a launcher and it is supposed to list all packages.
=> For me, only the applications who really need to access file storage as their main feature (like a gallery, file explorer, etc.) should have this permission listed.

The section about permissions is something that I always check before installing (or not) a new application and in my opinion most users should do it more often. Maintainers are very careful about it at F-Droid, but if you look in the Google store you can easily find applications asking for a crazy amount of permissions, most of them being way out of their scope (for example, I see many of the famous launchers with the "Full network access" and "Precise GPS location" permissions, sorry what?!).

---

Sorry for the long text, but at the end this feature will not implemented and I wanted to properly explain why.
I hope you are not too disappointed. For me, preserving the privacy aspect of this launcher is much more important than adding customization features (in a certain sense, privacy is also a feature by itself).

Best regards.

**Comment by dgcampea** [comment]
Completely understandable, there's value in having a launcher that requires only the minimal permissions to do what it does.
This feature request is probably best solved by having a separate app that only sets wallpapers if the permissions requested are to be kept as low as needed.

Thanks for looking into it, even if no changes were done.
