### ISSUE TITLE
Feature idea - Option to add icon to folder when long-pressing it

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#175]
Right now everything to do with folders is in Wrench menu > Folders.

When a folder exists, I think it makes it less menu-like to long-click icons to add them to available folders.

**Comment by comradekingu** [comment]
Somehow a + button to add icons inside folders makes a bit of sense, but I haven't thought about it much.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!
Due to the way things currently work internally, this may not be easy to implement without too much code duplication (which I try to avoid whenever possible) or display bugs (ex: folder not updating before being closed/opened again) which are currently handled by going to a different window, the one to manage folders, outside of the home screen.
I will have to think about it...

Note: an alternate way to access the window to manage folders is to click the title of any opened folder. Depending on the context, this might be quicker than going through the menu.

Best regards.

**Comment by falzonv** [comment]
Hello,

For information I made some good progress on this ticket, not finished yet but this should be part of the next release.

Best regards.

**Comment by falzonv** [comment]
Hello,

This has been implemented in new release v6.3.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.
