### ISSUE TITLE
Feature idea - Search field next to keyboard

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#176]
When searching for icons, the field to do so is up top.
![bilde](https://user-images.githubusercontent.com/13802408/151287301-e38fae39-49f3-4f78-975b-19ea86c2980c.png)

Without perfect control of where buttons are in a touch-typing scenario, this makes for more vertical eye-movement.
This is in line with the address field moved to the bottom in Android web browsers now
![bilde](https://user-images.githubusercontent.com/13802408/151287513-45bf15db-f926-4083-9fd5-709eb37fa0ce.png)

I think maybe the X isn't needed, as backspace from nothing or the Android controls should do it, vis-a-vis the folder menu.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion, I will have a look!

> Without perfect control of where buttons are in a touch-typing scenario, this makes for more vertical eye-movement.
This is in line with the address field moved to the bottom in Android web browsers now

=> Ah, I always wondered why the address bars were more and more to the bottom now. Personally I still always change it to top whenever possible but at least I now see the rationale about the default behavior :-)

> I think maybe the X isn't needed, as backspace from nothing or the Android controls should do it, vis-a-vis the folder menu.

=> I will keep the cross as it allows to close the Search popup directly (see #178).
Backspace from nothing to close the popup is not implemented because, with most keyboard (at least all those I had the occasion to test), maintaining backspace sends the key event repeatedly. So if the user maintains backspace to clear the current text, with the intention to enter a new one, it would probably closes the Search popup instead.
A way to mitigate this would be to track the delay between coming events to differentiate between a maintained backspace and a backspace when the field was already empty for at least X seconds. But this sounds a bit like over-engineering...

Best regards.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that I have found a solution to have the search field at bottom!
(with regards to my troubles described in the previous comment)

Even better, in the process I was able to make the Search popup height adapt to the number of search results!
These improvements to the Search popup may also solve most, if not all, of ticket #202.
Not sure yet when the next release will be published (many other work in progress), but this will be part of it :-)

Here is a demo below in 5 screenshots:
1. Search was just opened, all apps are displayed
2. Typing "m" reduces the number of results and the height
3. Typing "a" reduces the number of results and the height
4. Typing "p" gives only 1 remaining result (pressing the keyboard Search icon now would start the "Maps" app)
5. Adding a "z" gives no results. This provides a quick way to close the Search popup (typing anything to get no results makes the popup very tiny so it is easier to click above of it).

<img src="https://user-images.githubusercontent.com/4698531/159991813-c7f4beda-e4ce-4fcd-a3fa-fb341aa8e077.jpg" width ="19%"/> <img src="https://user-images.githubusercontent.com/4698531/159991816-f4ab42e0-d688-4c36-8562-5915eb19cee5.jpg" width ="19%"/> <img src="https://user-images.githubusercontent.com/4698531/159991818-4f78ca67-2fa5-4625-a32e-e747390fe9e3.jpg" width ="19%"/> <img src="https://user-images.githubusercontent.com/4698531/159991819-d61ccebf-b9ee-4bd3-8e9e-4db591abd208.jpg" width ="19%"/> <img src="https://user-images.githubusercontent.com/4698531/159997004-92ea8451-becf-4666-a638-3d0f920dd56f.jpg" width ="19%"/>

Best regards.

**Comment by xi7** [comment]
what happen if press enter that screenshot 2 ?

**Comment by falzonv** [comment]
Nothing special because more than 1 app is displayed at this stage.
But I made 5 screenshots only for the demo: in screenshot 2, any of the 8 apps can already be opened by clicking on its icon.

With the change from https://github.com/falzonv/discreet-launcher/issues/202#issuecomment-1079795992, the process will be even faster:
1. Search was opened and nothing is entered: all apps are displayed
2. "m" is entered: only 3 apps are displayed ("Maps", "Messaging" and "Music") => they can be opened by clicking on it
3. "a" is entered: only 1 app is displayed ("Maps") => it can be opened by clicking on it or pressing Enter

**Comment by falzonv** [comment]
> why u no open always the first position ? (best solution than break)

=> Ok, let's do this.
This indeed makes more sense now that the Search looks only at the beginning of the app name.
When it was looking everywhere in the name, there was a high chance that the first displayed app was not the one you want (in screenshot 2 it would launch "API Demos", and in screenshot 3 it would be "Gmail", not very useful if the user wants "Maps").

> nobody digit full name until show 1 app lol

=> As I said in another ticket, there is no need to enter the full name.
But to be honest I do not think many people use Enter to launch an app from the search results, they just click its icon.

**Comment by falzonv** [comment]
Hello,

What was described above has been implemented in v6.2.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by falzonv** [comment]
Since yesterday v6.2.0 is available on F-Droid so I will close this ticket.
