### ISSUE TITLE
Same height for top bar in folder and search

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#177]
Currently the folder top field is not the same size as the program search,
and there is a double-line forming the bottom of the program-search top field.

Proposed solution: same size for both fields, and a single line for both.

Preferred solution: Get rid of the field for folders and instead show its icon in a different colour when open (?).

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!

After further investigation, the additional line is part of the default Android TextView element but I agree it is not really necessary in this context. Since I found a way to hide it, this line will be removed in the next release which will, as you mentioned, also allow the search and folder titles to have the same height.

I do not plan to remove the folder title field. It is more explicit than something changing in the background, and this is also a shortcut to access the activity to manage folders from any open folder.

Best regards.

**Comment by falzonv** [comment]
Hello,

This has been implemented in new release v6.0.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by falzonv** [comment]
Hello,

Since yesterday v6.0.0 is available on F-Droid so I will close this ticket.

Best regards.
