### ISSUE TITLE
Feature idea - Quit directly from program search

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#178]
Currently it is possible to close down the keyboard and only be left with an open search.
It is no bigger, and for me it isn't in the same place, so it seems like the fold down button could be a triangle left right away(?)

**Comment by falzonv** [comment]
Hello,

Sorry this will not be possible because the first press on the Back button is actually handled by the keyboard itself, which makes it close. Then the next press on Back can be handled by Discreet Launcher, which makes the Search popup close.

However, the Search popup can be directly dismissed using the Close button (the cross in the upper-right corner). Since this makes the search text field disappear, the keyboard should close itself in the process.

Best regards.
