### ISSUE TITLE
Feature Idea - Sort folders and search to bottom in reversed mode

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#185]
In regular mode folders and the search is available at the top of the app view.
It is still at the top in reversed mode, which makes it a lot less accessible.
Edit: In terms of #186 the favourites are closed when swiping to the bottom of the screen when open.
Maybe that could open search instead?

**Comment by falzonv** [comment]
Hello,

I think I have an idea that should allow to move the folders and search at the end of the app drawer list when the layout is in reversed mode, instead of the beginning of the list currently.
The only drawback I see is that folders and search may also appear at the end in the selection dialog with check-boxes for favorites, but this is probably minor enough to be acceptable.
=> Will have to test this during the week...

> Edit: In terms of https://github.com/falzonv/discreet-launcher/issues/186 the favourites are closed when swiping to the bottom of the screen when open.
Maybe that could open search instead?

=> Not sure to understand exactly what you meant, but I do not plan to implement a special swipe to open the Search. You can however add the Search to favorites to open it faster (and by the way you can also add folders to favorites if needed).

Best regards.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been implemented in new release v6.1.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by comradekingu** [comment]
@falzonv Got it from F-Droid just now. Great stuff.

**Comment by pfertyk** [comment]
Hi! I've installed the new version of Discreet Launcher today and noticed this feature ;) While I understand the logic behind it, I realized that it kinda messed up the layout of applications I had before. Now the folders (where I put less useful apps) are easily reachable, while some of my frequently used apps ended up on top of the screen, outside the reach of my thumb :( I wouldn't suggest to reverse this feature, as the logic makes sense, but is there a chance it could be configurable?

Having said that, I would like to thank you very much for Discreet Launcher! The application is great: simple, elegant, and it helped me unclutter my screen and app list (with swipe shortcuts, favorites, and mostly folders). I've been trying to achieve this productivity level before and failed, but Discreet Launcher is just design for it ;) Thanks for a great program!

**Comment by falzonv** [comment]
Hello,

Thank you very much for your feedback, I am glad you like Discreet Launcher!

---

> I wouldn't suggest to reverse this feature, as the logic makes sense, but is there a chance it could be configurable?

=> I don't think I will make this configurable to be honest, because the point was precisely to make folders easily reachable.

However, here are some ideas that you may find interesting:
- Add some of the frequently used apps to favorites.
- The frequently used apps could also be placed in a folder but that needs an additional click... Unless the folder itself is selected as a favorite, then you just click it instead of opening the drawer.
- Very different idea, and maybe a bit weird but still possible: the app drawer is ordered alphabetically and apps can be renamed, so if you make some of them start with "y" or "z" they will appear at the bottom of the list (the reverse is true, if you add an "a" at the beginning of an app it would be displayed on top of the list).
- If there are some apps you really never use, you can hide them using the "Hidden apps" entry in Discreet Launcher menu.
- You could also reduce the number of folders for less useful apps. Since they are not used often it might not bring much value to sort them in too many folders. On my phone I use a single "Miscellaneous" folder (actually called "Divers" in French) for less useful apps that I still do not want to hide.

Best regards.

**Comment by pfertyk** [comment]
Hi! Thanks for getting back to me! And sorry to hear about no plans to add a checkbox for this feature :( I appreciate all the workarounds that you've listed, one of them might work for me. For now, I've settled for disabling updates in F-Droid for this particular app. Not the best solution, but the interface will stay familiar ;)

Thank you again for the amazing work on Discreet Launcher!
