### ISSUE TITLE
Feature idea - Reversed mode by default

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#186]
The new reversed mode is great.
Actually the favourites are accessible more of the time, because they start at the bottom.
The bottom is closer to the area the thumb covers in single-handed mode.
Needs #185 to have feature parity.

The alternative which may be good anyway is to start listing favourites in the middle of either the top or bottom screen.

**Comment by falzonv** [comment]
Hello,

I am glad you like the last improvements to the reversed mode :-)

However, although I may move its setting upper in "Operation" for better visibility, I do not plan to make this mode the default. The main reason is admittedly subjective, but personally I still prefer the regular mode.

> The alternative which may be good anyway is to start listing favourites in the middle of either the top or bottom screen.

=> Not sure to understand what you mean... For me this is already what happens with my 12 favorites (3 lines): they take about the upper half of the screen when the panel is opened, and the lower part if this is done in reversed mode.

Best regards.

**Comment by comradekingu** [comment]
@falzonv
The problem is the upper part of the screen isn't as accesible as the bottom.
When favourites start stacking from the top in regular mode, it means reversed mode is more ergonomic since they start from the bottom there.

The rationale is favourites is used more than the full app drawer.

So my part-way suggestion is to start stacking favourites in the middle of the screen in regular mode (but still think reversed by default is better.)

**Comment by falzonv** [comment]
Hello,

Thank you for the additional explanations.

I think the most important thing is that a reversed mode *exists* for users who prefer it (before v3.5.0 it was not the case).
Whether or not this is the default does not really matter as long as it can be easily configured in the settings.

Although it was published only in 2021, I use this launcher since I made its first draft in 2019 and I never had any issue with the favorites being on top. Perhaps this is because I use my phone with two hands most of the time, I agree the reversed mode is probably more convenient for someone who mostly uses his/her phone with one hand.

Even if users are probably more used to favorites being at the bottom (because this is what most launchers do), doing something different is not inherently bad, especially when the "usual" option is also offered.
It shows that other things can be possible, and may also be an incentive for users to look into the settings where they may discover other features they would not have noticed otherwise.

Having the favorites in the middle of the screen in regular mode would make the swipe up to close favorites less practical so I will not do this. But this should not be a big deal for you as you use the reversed mode anyway ;-)

Best regards.
