### ISSUE TITLE
Feature Idea - Home Screen Gestures

### ISSUE THREAD

**Issue by efdsys** [falzonv/discreet-launcher#189]
How about adding an option to "Swap Screen" (All<-->Favs) with Swipe left/right?

As we all know, swiping up/down opens and closes and is kind of a Discreet trademark.  But when searching for an app, this can be somewhat awkward.  For example:

- Swipe down to open Favorites and look for app
- Not found, swipe up to close
- Swipe up again to open All apps
- Not found --- must have missed it in Favs --- swipe down to close
- Swipe down again to open Favs again.

I proposal to allow the following to be configured as an *option* :

- Swipe down to open Favorites and look for app
- Not found, swipe left (or right) for All apps
- Still not found, swipe left (or right) to search Favs again

This may also be more intuitive for new users since this is closer to how the native Android launcher works. Swipe up to open, swipe left/right to change screens.   I know this is one of the first things I tried with Discreet.

**Comment by falzonv** [comment]
Hello,

Thank you for your interest in Discreet Launcher, your feedback and the suggestion!

You may have not noticed it yet but left/right swipes are already used for another purpose: at the bottom of the "Operation" settings you can assign apps to each of these swipes as a sort of shortcut (this was requested for easier use in car in #73).

Adding an option which conflicts with these options would probably add much more internal code complexity and potential bugs than added value, this is not something I will implement sorry.

I am also not sure the scenario you are describing would happen so often when someone uses the launcher daily:

- *Swipe down to open Favorites and look for app*
*Not found, swipe up to close*
=> Unless you have a lot of apps in favorites (which is possible), you would probably have a good idea upfront, before even opening the panel, of whether or not the app you are looking for is in this panel.
- *Swipe up again to open All apps*
*Not found --- must have missed it in Favs --- swipe down to close*
*Swipe down again to open Favs again.*
=> As its name implies, the "All apps" drawer really contains all apps and they are ordered alphabetically. An app cannot be in favorites while not being *somewhere* in the app drawer (more info in #184), either directly or inside a folder. For this latter case, there is always the Search app which searches also in folders and can be added to favorites (useful if you have a lot of apps).

> This may also be more intuitive for new users since this is closer to how the native Android launcher works. Swipe up to open, swipe left/right to change screens. I know this is one of the first things I tried with Discreet.

=> Not really because in the native Android launcher the gestures to open/close "All apps" are also vertical swipes. 
Indeed left/right swipes are used to change screens, but there are no screens in Discreet Launcher (actually there is one empty screen, a retractable panel for favorites, and the app drawer) so this is not really comparable.

Best regards.
