### ISSUE TITLE
Menu dissappears when more icons than can fit on one screen

### ISSUE THREAD

**Issue by AeOeAa** [falzonv/discreet-launcher#19]
Hi

Thanks for a great launcher!

I've had a few problems with not being able to select the "Hold here to access the menu" menu when there are more favourite applications selected than there's room for on one screen (must scroll to see them).

The first time it happened I had to uninstall and install, starting over, to get back to where I can get to the menu.

Today I found out that the launcher supports the horizontal screen position, and even when not choosing more favourites than will fit the vertical screen, on horizontal the screen will be full and the menu not shown.

**Comment by falzonv** [comment]
Hello,

Thank you very much for your feedback and bug report!

It seems that great minds think alike: I precisely applied a commit (ab77e00242757f34c5779e8e71ae68da68c6c9ef) to fix this issue yesterday evening :-)
This will be corrected in the next release v2.3.0 which is not yet published.

After unsuccessfully trying various things to solve this issue (\*), I noticed that a better solution was to limit the number of favorites and that 16 seemed a good number. It stays usable on a screen with a resolution of 480x800 and allows more favorites than most people will ever select (if someone really needs more than 16 favorites, (s)he may as well open the complete list).

*(\*) Even when setting a minimum size for the button it is still pushed outside the screen, surprisingly there is no good way to assign a maximum size to the list block if we want its height to remain flexible, etc.*

> The first time it happened I had to uninstall and install, starting over, to get back to where I can get to the menu.

=> Yes, for now the only other way is to clear the application data to remove all favorites (pressing the back button closes the favorites panel, then the complete applications list can be used to access the settings application — or do a long click on the Discreet Launcher icon to access directly its settings).

> Today I found out that the launcher supports the horizontal screen position, and even when not choosing more favourites than will fit the vertical screen, on horizontal the screen will be full and the menu not shown.

=> Indeed, and this will probably remains even with the limitation to 16 favorites (on my personal smartphone, 12 favorites are still ok in horizontal position but 16 would be too much and hide the button). However, a simple workaround is to turn the phone in vertical position when the menu must be accessed (probably not so frequent once the initial configuration is done).
=> If this really annoys you, I can try again to find another solution not based on favorites limit.

Best regards.

**Comment by AeOeAa** [comment]
Hello again

So, thanks for the update! A lot of good considerations. My issue wasn't really with the overflow of apps/favourites, but with the dissappearing menu that I didn't know where else to find.

Maybe I'm atypical for a discreet launcher type of guy 😂 but I've got way more than 16 favourites.

First let me tell you what happened after updating to v2.3.0. So, I read that there was a fix for this, and I hurried on github to read up on this issue. After that I went to my favourite panel and wondered why there wasn't any change, and I counted 26 favourites (yes 😊) which fitted nicely on my fullhd screen, still having the menu short cut at the bottom. Then I went to select favourites, scrolled to apply the already selected and now got the message that only 16 were allowed. OK, that's as described. But now I have half a screen empty and I'd much rather have my carefully selected favourites back 😅

So, it's really up to you where to go from here, I'm still happy with the launcher, and my next move is probably to try and use the "hide apps" feature to tuck away on the bloat in the All apps panel and try to use that more and then just have the most of the mostly used apps as favourites. (but I also have a lot of apps, and it's not a super fast way to get to the 6th app starting with s)

**Comment by falzonv** [comment]
Hello,

Thank you for the follow-up and explanations!

> Maybe I'm atypical for a discreet launcher type of guy :joy: but I've got way more than 16 favourites.

Haha, there are probably not enough users yet to define what is typical or not :-)

Before publishing it this year, I was already using this launcher on my phone since 2019.
Since one month that it is on F-Droid, I discovered many uses cases and many new features were added following discussions with users (long click open settings, notification menu, icon packs support, web shortcuts support, option to hide applications, transparent status bar option, automatic list update after addition/deletion, ...).

Honestly the launcher is much better now than in v1.0.0 and I learned many things about Android development in the process!

> now I have half a screen empty and I'd much rather have my carefully selected favourites back :sweat_smile:

Really sorry for that, I was far to imagine that you could have 26 favorites!
Out of curiosity, how many applications do you have?

When you mention an half-empty screen it gives me an idea which seems interesting enough to be tested:
Instead of hard-coding 16 favorites, maybe the maximum number could be calculated based on (a) the size of an icon, (b) the total screen height in vertical mode and (c) the space required to keep the menu operational.

I will reopen the ticket and try to implement this, it is a better idea than setting a fixed limit.

Best regards.

**Comment by falzonv** [comment]
Hello,

I was able to make it work and the next release v2.5.0 will adapt the maximum number of favorites to the screen size instead of using a fixed value of 16 (not sure how many it will be on your phone, but probably much more).

This new release v2.5.0 has been pushed to the stores few minutes ago and the usual publishing delay is:
- 1 or 2 days for Google Play
- 4 to 8 days for F-Droid

*Note: I will leave this ticket opened until the release is effectively published on both stores.*

Best regards.

**Comment by AeOeAa** [comment]
You're a wizard, can't wait to try it out 🙏😀

**Comment by falzonv** [comment]
Hello,

Seeing that release v2.5.0 has been published on F-Droid (in fact it is even v2.6.0 since yesterday), I will close this ticket but feel free to add comments if needed or wished.

Best regards.
