### ISSUE TITLE
Feature idea - notification dot

### ISSUE THREAD

**Issue by Xyguma** [falzonv/discreet-launcher#191]
Hi,

Thanks for this application. I'm new to github so I don't really know where to ask you something.

Anyway, I would love to be able to have the notification dots available with discreet launcher. I know it would necessite notifications access so maybe that's something you're not willing to do and I'll completely understand.

Thanks again for developping this app.

**Comment by falzonv** [comment]
Hello,

Thank you for your suggestion, I am glad you like Discreet Launcher!

I had a look for the notification dot and in fact it will not be compatible with how Discreet Launcher works internally: in order to minimize resources consumption and to display the app drawer as fast as technically possible, the list of apps and their icons is retrieved only on some events (start, install/remove app, switch icon pack, etc.).
The notification dot seems linked to the app icon (it is called "BadgedIcon" in the documentation) so it would require to update the list of icons every time the user navigates in the launcher for the dots to be properly added/removed. This update is by far the most consuming task of the launcher so I do not want to perform it so often.
Sorry this will not be implemented.

Best regards.
