### ISSUE TITLE
infinite bar vertical widgets

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#194]
https://user-images.githubusercontent.com/67331785/156904038-4932d64d-a3e9-4975-82e4-0d190f1d42fd.mp4

very useful and if u make with press and hold config height and remove from panel.

**Comment by xi7** [comment]
but why keep launcher incomplete , widgets and wallpaper are functions launcher.

**Comment by falzonv** [comment]
Hello,

From my point of view the launcher is already more than complete for a minimalist launcher.

Widgets are not going in the direction of having an empty home screen and the most appropriate app to set the wallpaper is not the launcher but the gallery because it already manages all the pictures and can conveniently show a "Set as" option.

In the F-Droid repository, I can also see many launchers that do not handle widgets or changes to the wallpaper:
- https://f-droid.org/fr/packages/com.github.postapczuk.lalauncher/
- https://f-droid.org/fr/packages/ademar.textlauncher/
- https://f-droid.org/fr/packages/com.github.rsteube.t4/
- https://f-droid.org/fr/packages/ru.henridellal.emerald/
- https://f-droid.org/fr/packages/io.github.subhamtyagi.lastlauncher/
- https://f-droid.org/fr/packages/com.anpmech.launcher/
- https://f-droid.org/fr/packages/com.sduduzog.slimlauncher/
- and probably more (I stopped at the middle of page 2 out of 7)

Of course the most famous launchers in Google Play have tons of features (which allows them to ask for tons of unnecessary permissions), but that doesn't mean simpler things cannot exist.

Best regards.

**Comment by xi7** [comment]
the widgets by side bar is not at home screen and will keep empty... loading like favorites, very discreet and different on the market.

very useful for quick access like:
temperature and clock,
stocks,
News,
calendar
and  more...

**Comment by falzonv** [comment]
All of this can already be accessed from the related apps, which can be put in favorites if accessed often.
If you really need to see all of this at the same time, Discreet Launcher is probably not the best choice because it aims to be a minimalist and distraction-free launcher.

**Comment by xi7** [comment]
i still don't understand how widgets are considered distractions.

example, if i need check stocks i will need click swipe favorites - find the app - login - search stocks..... while widgets show fast what u need with easy gesture. 

how part of an application's functionality is considered distraction

**Comment by falzonv** [comment]
Hello,

I guess due to barrier language I am not able to properly express what I mean. Widgets for news or stocks tend to introduce what is called fear of missing out (FOMO, https://en.wikipedia.org/wiki/Fear_of_missing_out), which often results in unnecessary anxiety.

> example, if i need check stocks i will need click swipe favorites - find the app - login - search stocks..... while widgets show fast what u need with easy gesture.

A good stocks app should allow you to check stocks directly (no need to login each time you open the app ; ideally no login at all for view-mode) and to select favorite stocks (no need to search for them each time).

To skip the part "swipe favorites + find the app", you could assign the stocks app to one of the horizontal swipes. That way, you could open it directly from the home screen (with a swipe towards right for example).

And if you use the stocks app often it will most likely always be in your recent apps, so it should load even quicker (no need for Android to recreate the whole activity, it only performs a "resume" action).

Best regards.
