### ISSUE TITLE
Bug? - The Android nav buttons change colour

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#198]
App drawer open:
Triangle gray, square gray, square light gray

Desktop screen open:
Triangle dark gray, square dark gray, square light gray

Favourites open
Triangle gray, square gray, square light gray

It is also a bit flakey to open the nav buttons, as they aren't always shown.
Did I mess up with the settings?

**Comment by falzonv** [comment]
Hello,

The only setting that does something on navigation bar buttons is "Dark status bar icons", starting with Android 8 it updates the navigation bar buttons accordingly. I could disable this last part, but with the light wallpaper use case from #142 I think it looks better to update both status and navigation bars at the same time.
*(It can be done only starting with Android 8 because previous Android versions do not allow to update the navigation bar, only the status bar can be changed starting with Android 6 ; which is why the setting mentions only status bar but this is not perfect).*

For information there is not much room for customization as the system only allows a dark or light toggle of the whole navigation bar, it is not possible to set a specific color or to apply the change to only one of the three buttons for example.

But there are other strange things in your report that this setting cannot explain:
- The dark/light colors of the buttons are changing when you navigate in the app, but the setting applies globally and does not make any difference between home screen, favorites open/closed, or app drawer (in these 3 places, the buttons are either globally set to light or globally set to dark, according to the setting).
- One of the buttons has a different color than the others. I didn't even know this was possible, this is for sure not something that I can set from my side (the system probably can, but I do not see why it would "forget" a button).

Unfortunately I do not think this is a bug I will be able to solve, sorry.
Maybe try to play with the "Dark status bar icons" setting, it may at least make some of the buttons more visible.

Best regards.

**Comment by comradekingu** [comment]
Turning off "Dark status bar icons" makes them all white.
I will make a video if I can figure it out.
