### ISSUE TITLE
Grid problem with Android 12

### ISSUE THREAD

**Issue by tuch96** [falzonv/discreet-launcher#199]
Hi Vincent,

I really hope you are well. I'm trying out Android 12 right now. When I change the grid in the android settings (Design), the discreet launcher does not adopt this setting. It always stays in 4 columns.

Best regards, Marc

![Screenshot_20220317-182810](https://user-images.githubusercontent.com/57192210/158869241-d8829d82-8515-4978-99b4-6e3313957f23.png)
![Screenshot_20220317-182730](https://user-images.githubusercontent.com/57192210/158869251-32304df4-1d9e-40a5-ab9d-88db95cea794.png)
![Screenshot_20220317-182703](https://user-images.githubusercontent.com/57192210/158869255-5dbda99d-be95-47f3-9876-bb8eedf53595.png)

**Comment by falzonv** [comment]
Hi Marc,

Yes I am ok, thank you for asking :-)
Much more busy with my job than few months ago to be honest. Last year I had many unemployment days (almost every Friday) due to Covid savings in my company and now I work full time again. A lot of the Discreet Launcher developments happened on these Fridays so now I have much less time to work on it.

I hope you are doing well too!

Coming back to the grid size setting, after further investigation it is in fact a setting of the Pixel stock launcher. It is a bit strange and rather confusing that they put it in the Android settings instead of the Pixel Launcher settings.

For information, the number of columns in Discreet Launcher is not fixed but based on the screen width. It will change according to portrait/landscape orientation, and can also be affected by the "Display size" in Android settings (not sure of the exact setting name but this should be located in the Screen/Display settings).

By the way you may be one of the firsts users to test the launcher on Android 12.
My most recent emulator is still using Android 11 :-)

Best regards.
