### ISSUE TITLE
Icônes pack.

### ISSUE THREAD

**Issue by porosjp** [falzonv/discreet-launcher#2]
How can I change the icons pack? To Articons pack by example. Thanks.

**Comment by falzonv** [comment]
Hello,

Currently this is not implemented (not intentionally but because I never use icon packs and forgot about this use case...).
The request is well noted, I will work on it and keep you updated.

So, as a to-do list for myself:
- [ ] Find a way to retrieve all installed icon packs
- [ ] Create a "Settings" menu (could be useful for future things) in which one of these icon packs can be selected (+ option "None" if for some reasons the user prefers the native icons)
- [ ] Find a way to load the icons from the selected icon pack instead of the native icons

Best regards.

**Comment by porosjp** [comment]
Merci beaucoup . Bon travail

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by falzonv** [comment]
*Bon, ça fonctionne !
Je continue en anglais au cas où des non-francophones liraient ce ticket plus tard.*

Icon pack support is now implemented in release v1.1.0 which has been pushed to GitHub few minutes ago.
This will probably take a couple of days to be fully replicated in the F-Droid repository.

It worked fine when testing with [Arcticons](https://github.com/Donnnno/Arcticons), [Ameixa Monochrome](https://gitlab.com/xphnx/ameixa) and [MBE Style](https://github.com/iAcn/MBEStyle) (icon packs on F-Droid) so I think it should work with most icon packs as long as they follow the format given in [this guide to create icon packs](https://forum.xda-developers.com/t/guide-how-to-create-icon-packs-for-go-nova-apex-holo-adw-launcherpro-xperiahome.2399426/) which seems to be a standard.

Best regards.

**Comment by falzonv** [comment]
Hello,

For information, release v1.1.0 is now available on F-Droid since yesterday 14th March (it took 4 days from the GitHub push to availability in the repository).
Since it is now resolved, I will close the ticket but feel free to add comments or open it again if needed.

Best regards.

**Comment by porosjp** [comment]
It works! Thank you

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by falzonv** [comment]
Thank you very much for the confirmation!

Bonne fin de journée
