### ISSUE TITLE
Feature Idea - Double Click the Home Screen to Turn of Screen

### ISSUE THREAD

**Issue by r3veal** [falzonv/discreet-launcher#200]
It would be wonderful if when you double-click the home screen, your screen turns off, as the title suggests.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!

However, as explained in ticket #48, a special admin permission is required to put the device into sleep mode. This is probably for security, as some bad apps could block the phone by putting it to sleep when opening the app (so when the user unlocks the app is shown again and it put the phone back in sleep mode, and so on).

Since I want to limit permissions to only what is strictly mandatory, this will not be implemented.
(Currently, the only permission requested by Discreet Launcher is QUERY_ALL_PACKAGES.)

---

Looking again in ticket #48, I see that I also wrote:

> By the way, while searching, I came across an app called "Easy Lock" which may interest you because it even has a mode "double tap to sleep from any application":
https://forum.xda-developers.com/t/app-4-0-material-easy-lock-double-tap-status-bar-nav-bar-to-sleep.3222024/
>
> *Disclaimer: I have not tested this application (only looked at its [source code](https://github.com/aravindsagar/EasyLock) to check permissions and the way to go in sleep mode) and many users report that it doesn't work perfectly for them (for example after the phone is in sleep mode they cannot unlock with the fingerprint, have to use another method).*

The disclaimer is still true (never tested the app myself, only looked a small part of the code, potential bugs, etc.), but you may still be interested by the app so I mention it just in case.

Best regards.

**Comment by qguv** [comment]
Currently, users can select an app to be run when they swipe left or right on the home screen. Would you consider making the double-tap gesture configurable in the same way? @r3veal could then configure the double-tap gesture to launch an app (of which there are several) whose sole purpose is to lock the screen. Other users could use it for other purposes, like firing a task in tasker.

Is this something you'd consider @falzonv ?

Thanks!

**Comment by falzonv** [comment]
Hello @qguv,

Interesting idea, I will think about it :-)
Created ticket #204 for follow-up.

Note: actually what you described using a dedicated app can also be done with the current swipes (instead of "double tap to lock", it would be "swipe left/right to lock").

Best regards.
