### ISSUE TITLE
Icon for web apps

### ISSUE THREAD

**Issue by mkofahl** [falzonv/discreet-launcher#21]
Since #16 there has been the possibility to create shortcuts to webapps. These are currently displayed with the app symbol (e.g. Chromium). However, other launchers show the webapp's icon (favicon). In order to better distinguish the webapps, the Discreet Launcher should also display the icon of the webapp.

**Comment by falzonv** [comment]
Hello,

Thank you for your feedback!

Indeed, currently a generic icon is used because at first I wanted to focus on implementing the web applications support itself.
This was quite difficult because there is very few documentation and it was needed to dig in the Android source code to make it work (if interested, you can read more details in the two long messages of ticket #16).

But now it works quite well!
So we can indeed continue with adding the web app icons.

It will probably take some time to implement but globally two things must be done:
- Android < 8 : the icon is provided only when the shortcut is added, it must be saved in the launcher files to be displayed later
- Android >= 8 : the Android system keeps all information about shortcuts internally so it is probably better to ask for the icon each time the application list is updated

Best regards.

**Comment by falzonv** [comment]
Hello @mkofahl, @johanbove,

Regarding icons for web apps, I come back to you with a good news and a bad news...

The good news is that I was able to make it work and **it will be part of release v2.5.0!**
Finally both cases are managed in the same way (the "Android < 8" way) and the icons are even included in the export file (export/import feature added in v2.4.0).

Now, the "bad news" is that the only moment where I can "catch" the icon to store it in files is at the shortcut creation. It means that the icons will appear only for the *new* shortcuts, and not for the shortcuts already existing (so if you want the icon, you will have to remove the shortcut and add it again...).
If for some reasons no icon is received at the shortcut creation, the current generic icon will be used as fallback.

This new release v2.5.0 has been pushed to the stores few minutes ago and the usual publishing delay is:
- 1 to 2 days for Google Play
- 4 to 8 days for F-Droid

*Note: I will leave this ticket opened until the release is effectively published on both stores.*

Best regards.

**Comment by falzonv** [comment]
Hello,

Seeing that release v2.5.0 has been published on F-Droid (in fact it is even v2.6.0 since yesterday), I will close this ticket but feel free to add comments if needed or wished.

Best regards.

**Comment by johanbove** [comment]
Thanks. The icons show up nicely. Testing in 2.6.0.

**Comment by falzonv** [comment]
Great, thank you for the confirmation!
(and sorry again for bug introduced at the same time, relating to #28 :-/)
