### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#210]
Hello,

Long story short, due to changes in my professional life, I now have very little time to work on Discreet Launcher.
The development will continue, but at a much slower pace.

You can find more details below.

------------------------------------------------------------

Due to cost savings related to Covid-19, I was unemployed on Fridays since January 2021 and I used that time to work on Discreet Launcher. Since March 2022, the situation changed and I am working full time again, which means I can no longer dedicate that much hours per week to this project.

After releasing Discreet Launcher a year ago, I soon realized that being an open source maintainer is more like a second job than a hobby as many users request changes, give ideas and write me all kinds of messages. I try to answer to everyone and improve Discreet Launcher according to requests but it takes a lot of time, much more than just doing general maintenance.

I will continue to do so, but at a much slower pace now that my spare time has decreased significantly.

Finally, let's take this message as an opportunity to make a status of the project:
- Discreet Launcher is developed in Java, supports Android 5 to 11, and is translated into six languages (English, French, German, Indonesian, Norwegian and Russian).
- I have no idea on the number of users with F-Droid, but there are currently a bit more than 230 users with Google Play.
- With regards to privacy, a single permission is requested in order to get the list of installed apps.
- The APK file size is less than 2 MB.
- Although it is probably not perfect, I consider the codebase to be sane, well commented and with no major bugs.
- With v6.2.2, a total of 50 versions have already been released!

Thank you for reading and for your interest in Discreet Launcher!

Best regards.

**Comment by daviddickerson** [comment]
Greetings, Vincent!

First of all, _thank you_ for developing Discreet Launcher, plus your other free/libre software and scripts.

Apology: I realize the issues section of this repository is not appropriate for expressing my thanks -- but you deserve a public thanks and a standard e-mail message is as private as a postcard (the reason for encryption and other tools), but I want to thank you here, because I am not alone.

As a user of [Debian GNU/Linux](https://www.debian.org/)  (a secure and stable all-volunteer distribution), [GNU.org](https://www.gnu.org/) /[FSF.org](https://www.fsf.org/)  software (Linux desktop and server), and the free/libre software on my Samsung phone to replace the proprietary apps I cannot delete without "rooting" the device, I have benefited daily and for years (and for decades with Debian) from quality, hard work such as yours, Vincent.

Congratulations on finding full-time employment again, Vincent! I hope you find your work fulfilling -- and understand that you clearly have less time for your free software projects.

Regarding the contribution needs stated in this maintenance status of Discreet Launcher, the human languages I have learned, besides my native English, are "rusty" at best, although I wish I could volunteer by translating.

If (as) you think of other opportunities to volunteer, however, Vincent -- and I understand your wish to stay in control of the Java source code -- I am not alone in wanting to contribute as a volunteer -- to any of your free (open source) projects.

(Note: Although I know Android apps typically do not require extensive documentation, Vincent, I have professionally written printed manuals and on-line/electronic documentation for more decades than I care to admit, and I have also done QA/testing and Web design. Of course, no one reads documentation or -- to be fair -- few users read manuals.😉)

Thank you, again, Vincent. Please consider my offer to contribute to any your open-source projects as a standing one, barring life's capricious way of demanding our time.

Cordially,

David Dickerson

**Comment by daviddickerson** [comment]
Hello, Vincent!

I apologize for my lengthy delay in responding to your message of June 1, which I just read today. (Life, as you know, can get hectic and adversity, of course, typically arrives with no warning. 😀)

I would be happy to reread the Help section of Discreet Launcher and provide feedback.

I will remind myself to include the feedback as a new issue. Given my allusions above to life's capricious nature, my response may not be immediate, but I appreciate the invitation to contribute -- and, _especially_, your ongoing dedication to Discreet Launcher, despite your busy professional work -- and am honored by your request.

With best wishes --

Cordially,

David

**Comment by nanerc3** [comment]
hello

Since there is no other place to write sentences, I will report a bug even though it is v7.2.0

It seems that the history screen was accidentally split screen and the upper app was deleted
After that, only the top third of the history screen is displayed on the bottom of smartphone screen

After that, I returned to the home app that was originally included in the smartphone and fixed it by tampering with the division, but I will just report it

**Comment by falzonv** [comment]
Closed in favor of ticket #314
