### ISSUE TITLE
Unrecognised apps

### ISSUE THREAD

**Issue by jrm72** [falzonv/discreet-launcher#228]
Hello,

I have installed discreet launcher on a Poco X4 and some of my installed apps that appear in the Poco launcher do not appear in Discreet Launcher.

**Comment by falzonv** [comment]
Hello,

Thank you for the report, could you provide a bit more information?

For example:
- Do you observe the same with another custom launcher? (ideally a launcher from F-Droid so that I can see its source code)
- What are the names of these apps?
- If possible, what are the package names of these apps? (sometimes it can be found in the app settings)
- Which Android version are you using?

Currently the only thing that I can think of is that the system hides some apps to third-party launchers. Not sure why it would do that but this would explain why only the Poco launcher (which is a system app) can see them.

Best regards.
