### ISSUE TITLE
The ability to manually select an icon for each app

### ISSUE THREAD

**Issue by KazKaz90** [falzonv/discreet-launcher#231]

**Comment by falzonv** [comment]
Hello,

Thank you for your interest in Discreet Launcher!

In #112, #137 and #162, I said that customize app icons further than selecting a pack is out of the scope of Discreet Launcher (for history, icon packs were not even supported before v1.1.0 ; it was quite a challenge to implement).
With tickets #130 the possibility to combine two icon packs was added, and in #149 the possibility to globally color all icons not covered by icon packs was implemented for more complete coverage.
I still don't plan to work on customizable icon for each app as it would introduce too much code complexity and potential bugs.

The ticket #203 mentions the app IconPackStudio which allows to create custom icon packs. I made some adjustments to Discreet Launcher in order to be more compatible with this app but never got a feedback if it worked. You may try if you want.

Best regards.
