### ISSUE TITLE
Open clock/calendar when clicking time/date

### ISSUE THREAD

**Issue by kariboooooo** [falzonv/discreet-launcher#238]
. Clock click > change clock app
. Date click > change calendar app

**Comment by falzonv** [comment]
Hello,

Thank you for your interest in Discreet Launcher and your suggestion!

However, I am not sure to understand the use case:
Most users probably have only one clock app and one agenda app, so adding features in the launcher to switch between these apps seems quite overkill (also, the default apps are supposed to be managed by the system, not by the launcher).

Could you please clarify your request?

Best regards.

**Comment by kariboooooo** [comment]
Hello,

Thanks for ur answer!

1. The display time is static in your (nice) launcher: i can't perform any
action. Only read time.

My request is really simple: just click on the clock (display time) to
access the app, then to choose between alarm, timer, stopwatch...

2. The same request about calendar: from static display to clickable
display date. (To manage events, reminders... directly from the display
date.)

Regards,
K.

**Comment by falzonv** [comment]
Hello,

Sorry for the late reply, I was away last weeks.

Now I understand what you mean, thank you for the clarification :-)
This is a good idea, I will have to check if this is feasible as the code to display the time and date is a bit special.

Best regards.

**Comment by kariboooooo** [comment]
Thanks!

**Comment by falzonv** [comment]
Hello @kariboooooo,

It has been a very long time but I am pleased to inform you that this has been implemented in new release v6.6.0!

A couple of remarks:

1/ The new setting is in "Operation > Interactive clock" and disabled by default to not confuse existing users.

2/ For the Calendar, there should be no issue as Android provides a (not so easy to find) way to call the default Calendar app.

3/ For the Clock, it was more complicated because there is no default Clock app in Android. There is of course the stock Clock app and users can install third-party Clock apps, but none of them can be selected as "default" in the sense of "default browser" or "default SMS/MMS app".
Managing third-party Clock apps would introduce too much code complexity so I decided to focus on the stock Clock app:
When the time is clicked with the option enabled, Discreet Launcher tries to open "com.google.android.deskclock" (for recent Android versions) or "com.android.deskclock" (for older Android versions, and LineageOS) depending what is found. If none is found or if the stock Clock app is disabled, an error message is displayed.

---

The release v6.6.0 has been published few minutes ago.
Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by jbatt33** [comment]
Instead of an error, can a dialog appear with the list of apps and the user selectes the desired clock app?

**Comment by WarmChocolateCake** [comment]
Just tried this out (installed via F-Droid on Android 11)
I love the idea, but I think you have now created work for yourself 🙂  - I can open neither clock nor calendar

Tapping on the time gives me: `Could not find  "com.android.deskclock"`
Tapping on the date gives me: `Could not find "{calendar}"`

I have actively disabled the Google apps and use Tibor's SimpleCalendar and SimpleClock apps: https://www.simplemobiletools.com

So, in my case, I'd love it if I could select those apps from a list.

**Comment by falzonv** [comment]
Hello @jbatt33, @WarmChocolateCake,

Thank you for your reports!

For the Clock I will have a look, I am not sure yet how to identify clock apps to build a relevant list (maybe by searching apps having the permission to set alarms, but this would probably include other things than clocks...).

There is an issue with Simple Calendar not being detected as a calendar app (not only by Discreet Launcher), I added information in the related ticket (https://github.com/SimpleMobileTools/Simple-Calendar/issues/1859) but this is not something I can solve on my side.

Best regards

**Comment by falzonv** [comment]
> maybe by searching apps having the permission to set alarms

After further thinking, I am not sure my app would be allowed to check this or that it would be future-proof. A simpler and better idea is probably to look for package name containing the words "clock" or "alarm", this should take care of most cases:

> com.simplemobiletools.**clock**
com.better.**alarm**
com.android.desk**clock**
com.google.android.desk**clock**

Remark: just so that you are not surprised, I should mention that the next release will probably not come before one or two months as I am currently very busy with my job.

**Comment by falzonv** [comment]
Hello,

An option to select the clock app has been added in new release v7.0.1!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.
