### ISSUE TITLE
Improve the "Hold here to access the menu" button

### ISSUE THREAD

**Issue by tuch96** [falzonv/discreet-launcher#24]
A really great minimalist launcher. A few suggestions. It would be great to disable the texts under the app icons. And it is possible to customise the menu text "hold here to...". A function to deactivate the top text "Applications (List....)" in the app overview.

Many thanks!!

**Comment by falzonv** [comment]
Hello,

Thank you very much for your feedback and suggestions!

> 1/ It would be great to disable the texts under the app icons.

=> Yes it could even be a setting with 3 options allowing to display (a) "Icons and texts", (b) "Icons only" or (c) "Texts only".
The default value would be "Icons and texts" as it is today.
I will rename this ticket and we will keep it for follow-up about this new setting.

> 2/ And it is possible to customise the menu text "hold here to..."

=> Not sure to understand that part, what would you like to change with the menu button?

> 3/ A function to deactivate the top text "Applications (List....)" in the app overview.

=> Ok for me, I created ticket #25 for follow-up of this point.

For points 1/ and 3/, I will see how to do it and keep you updated.

Best regards.

**Comment by tuch96** [comment]
2/ And it is possible to customise the menu text "hold here to..."

=> Not sure to understand that part, what would you like to change with the menu button?

I mean the text below the favorites applications list ("Hold here to access the menu". If we could change the text for example, to "Menu" or an other text. Maybe also implement an icon? Like in the web area as a burger menu icon.

**Comment by falzonv** [comment]
Hello,

Ok thank you for the explanation.
I made some tests today and here are the results:

- It does not seem possible to use the burger icon with my button: building the application fails because the burger icon provided with Android is marked as "private" (I guess it is restricted to some types of menu bars only, not floating buttons)
- However, I was able to find a "more" icon which looks quite good (see screenshot below)
- Maybe because I have big fingers, but I found that if the text is only "Menu" the button is much too small
- With something like "Access the menu", the proportions seem to look better (see screenshot below)

What do you think of the example below?

![2021-04-14_access_menu_button](https://user-images.githubusercontent.com/4698531/114744916-7754fb00-9d4e-11eb-8e77-876e385876b2.jpg)

I will also make edits to allow opening the menu with a short click (since the "Hold here" mention is not there anymore).

Best regards.

*Note: finally I created #26 to follow-up the icons and texts in the applications list, and we will keep this one for the menu.*

**Comment by tuch96** [comment]
Perfect! It is better for the usability and It looks better in terms of design.

An additional solution could also be a menu button directly in the Favourites app overview. If the app icon of your app routes directly to the settings when clicked. Then you could remove the bottom line completely. But maybe that's not good for the app usability?!? What do you think?

![img3](https://user-images.githubusercontent.com/57192210/114764253-028cbb80-9d64-11eb-88eb-4395704b9f64.jpg)

**Comment by falzonv** [comment]
Thank you for your feedback and new suggestion :-)

From my point of view this is more intuitive to have a real menu button than to use the launcher icon as menu. It also avoids to take a slot from the favorites panel, so the user can really have only the icons (s)he selected.

*Note: I didn't know that my launcher was already in Arcticons, nice!
It was one of the packs I used when implementing icon packs support by the way (back in ticket #2).*

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that the new menu button has been implemented in release v3.0.0!

This new release v3.0.0 has been pushed to the stores few minutes ago and the usual publishing delay is:

- 0 to 2 days for Google Play
- 4 to 8 days for F-Droid

*Note: I will leave this ticket opened until the release is effectively published on both stores.*

Best regards.

**Comment by tuch96** [comment]
Hej! Thanks for the info and I am very excited and will report as soon as the new version is released on F-droid.

**Comment by falzonv** [comment]
Hello,

This release being now available on F-Droid, I will close this ticket.
Feel free to add comments if needed :-)

Best regards.

**Comment by AeOeAa** [comment]
I think this is great. It may be excessive to personalise it, but a nice to have could be to allow for just the icon or a custom label in Settings > Customization > Display.

**Comment by falzonv** [comment]
Perhaps in the future, for now I do not plan to add these options as there are already many things to do.
By the way, if the "smiley selection for folder icon" idea from ticket #35 works, it could also be applied for this menu button icon...
