### ISSUE TITLE
Access notification panel via pull-down gesture

### ISSUE THREAD

**Issue by jaytohe** [falzonv/discreet-launcher#240]
Hi Vincent,

Firstly, thank you for your work on this great launcher. Been using it for a few days now and I really like it!

One thing I do miss though -that other launchers offer- is the ability to swipe down in order to access the notification panel. I use the launcher with the "reversed interface" and "no app drawer" toggled on, so swiping down to open notifications makes sense in that case. 

Maybe, it'd be better if instead of having a "reversed interface" toggle to make the swipe down/up gestures user-configurable (like the swipe left/right). What are your thoughts?

**Comment by falzonv** [comment]
Hello,

Thank you for your message, I am glad you like Discreet Launcher!

> One thing I do miss though -that other launchers offer- is the ability to swipe down in order to access the notification panel. I use the launcher with the "reversed interface" and "no app drawer" toggled on, so swiping down to open notifications makes sense in that case.

After searching in the Android documentation and across Internet, manipulating the notification panel from an app doesn't seem officially supported. There is a hack to do it via an undocumented function and after adding a permission, which is probably how the other launchers you used are doing it.
To be honest I am not really fan of these kind of hacks because they may not work in all Android versions or all devices. I also want to keep the required permissions to the strict minimum (currently there is only one permission which is needed to display the list of installed apps in Android 11 and beyond) so this will not be implemented.

**Possible workaround:**
On Google Play, I see there are some apps (and probably others) that work as a shortcut to open the notification panel:
https://play.google.com/store/apps/details?id=jp.neap.opennotifications
https://play.google.com/store/apps/details?id=com.stihiya.notification.drawer&hl=en_US&gl=US
=> Never tested myself (I only have F-Droid on my phone), but if you are using Google Play maybe you could install one of them and assign it to one of the Discreet Launcher home screen gestures to launch apps (swipe left/right, double tap)?

---

> Maybe, it'd be better if instead of having a "reversed interface" toggle to make the swipe down/up gestures user-configurable (like the swipe left/right). What are your thoughts?

I thought about it at some point (while implementing the reversed interface), but realized it would add a lot of code complexity to handle all the cases without too many issues. Then the horizontal swipes as shortcuts to open apps were added so now it would be even more complex if we wanted to do it. I prefer to keep the project simpler to manage for better stability.

Best regards
