### ISSUE TITLE
[Feature Request] Hide/unhide apps from the long press menu

### ISSUE THREAD

**Issue by jcperil** [falzonv/discreet-launcher#243]
Low priority. An option to hide/unhide an app when you long press the app icon. Similar to Add to/Remove from favorites.

Attachment:
![hide unhide](https://user-images.githubusercontent.com/89805719/195632534-41679769-3fbb-490c-a6e9-9dedc2e1bc26.png)

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!

However, I will not implement it for the following reasons:
- "Unhide" is not possible because hidden apps do not appear anymore in the app list (that's the point of hiding them). Hidden apps can be unhidden in the "Hidden apps" menu, they appear on top of the list to make it easier.
- "Hide" is possible but I am not convinced this will be an improvement:
  - The hidden apps feature is mainly to get rid of bloatware apps that cannot be uninstalled or disabled, users will most probably do it once when they get a new phone then never need it again.
  - Some users have older phones with small screens so it will make the long press dialog even bigger for a not so used option (as per previous point).
  - In case of a mis-click, the user may wonder if they accidentally deleted the app from their phone (of course no launcher is capable of doing that, but less technical users may think it can).

Best regards.

**Comment by antodc** [comment]
I know the development of the app is somewhat in stand-by mode. However, if at some point in the future the developer could find again time and willingness to work on it, I think that adding the possibility to hide apps by long pressing on them would be a very nice improvement.
In my case, I have a few apps whose name is the same (say, 'Calculator', 'Calendar', 'Phone', 'Messages') and from the list that appears for hiding apps it is not easy to identify the one you really want to hide. Using the icons would be much easier.
'Unhide' could remain as it is now.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion, however after reading again my closure comment from 2022, I think the points I raised at the time are still valid.

Ideally there would be small icons next to the names in the pick list but I was never able to make this work with the AndroidX framework (which allows compatibility with older Android versions).

A workaround to identify the duplicate-name apps to hide in the list would be to add something to their names before going into the list (with long press on the app icon and "Rename"), something like "Default Calculator", "Calculator2", "Calculator-" or whatever makes sense or is easy to type (the app will be hidden anyway).

If this is in the process of replacing default apps, another way could be to disable these default apps (they usually cannot be uninstalled), which will make them disappear everywhere in Discreet Launcher and will also prevent the system from trying to update them.
Since there is no reliable system signal when an app is enabled/disabled (more details in ticket #311), you would have to refresh the app list from the main menu or wait for it to be refreshed on another event (such as an app install/remove/rename, favorite or folder change, ...).

You may also group these default apps in a folder, this is what I do for apps that I very rarely use but are still needed once in a while.
That way there are not visible in the main app list, but still accessible without having to handle hide/unhide (which is more intended for "permanent hide" such as bloatware apps that cannot be disabled).

Best regards.

**Comment by antodc** [comment]
Thank you for your suggestions!
I am not used to change app names and, to my shame, I did not think of this simple solution.
Unfortunately, I cannot disable all of those apps as I found out that some synchronisation services do not work properly without some of them.
And yes, I already have my ‘garbage’ folder where to keep the ones I cannot disable. Another big advantage from DL, that allows the creation of folders.
