### ISSUE TITLE
F-Droid build v6.6.0 failed

### ISSUE THREAD

**Issue by linsui** [falzonv/discreet-launcher#248]
https://monitor.f-droid.org/builds/log/com.vincent_falzon.discreetlauncher/54#site-footer

https://issuetracker.google.com/issues/184872412 This is an issue of AGP 4.1. Updating AGP to 4.2 or above should fix it. Could you please upgrade the AGP? Thanks!

**Comment by falzonv** [comment]
Hello @linsui,

Thank you for the report and sorry for the delay answering, I see your message only now.

I am a bit confused because in the meantime (27/10) I published v6.6.1 and the build was successful although I changed nothing about AGP (having not seen your message yet):
https://monitor.f-droid.org/builds/log/com.vincent_falzon.discreetlauncher/55#site-footer

Quite strange... but I will have a look to upgrade AGP for better stability.

Best regards.

**Comment by linsui** [comment]
> I am a bit confused because in the meantime (27/10) I published v6.6.1 and the build was successful although I changed nothing about AGP (having not seen your message yet):

I don't know the reason, either. This error only happens after our buildserver upgrade from stretch to bullseye.

**Comment by falzonv** [comment]
Hello,

For information my new release v7.0.1 (pushed to GitHub few minutes ago) now uses AGP 7.3.1.
There should be no issue this time :-)

Best regards.
