### ISSUE TITLE
Grafical issue with clock

### ISSUE THREAD

**Issue by AlphaElwedritsch** [falzonv/discreet-launcher#255]
In the default settings, the clock is hidden from the APP drawer. However, the favorites bar does not do this.
I think this is a graphic bug. See screenshots.

Many greetings

<img width="30%" src="https://user-images.githubusercontent.com/109347938/200143906-618e39c4-41d9-4b89-81c3-8765f44134b7.png"/> <img width="30%" src="https://user-images.githubusercontent.com/109347938/200143911-ec37cf25-fff0-44d5-8f60-4fc1d103ef8b.png"/> <img width="30%" src="https://user-images.githubusercontent.com/109347938/200143910-c9755880-02bc-4d66-b8ff-ee54507aa7b1.png"/>

**Comment by queria** [comment]
When favorites are shown, homeScreen is not hidden, seems it could be easy to add that.
But i guess there may be reason that it is intentionally left visible - as e.g. in case clock is placed at bottom (my case for ex.) and favorites at upper edge it looks better if clock does not disappear?

But then it depends first if clock/favorites are on same edge, or if there is enough favorites to make it long enough to overlap.

So unless always hiding clock when favorites are shown is acceptable (is it?),
maybe it can be hidden only if clock view overlaps (intersects) with favorites one - though if i'm reading the code correctly, clock view is across whole home screen - and position of visible clock/datetime is calculated in onDraw? (Maybe it could be pre-calculated only at specific times - like settings change/screen rotation etc? and stored inside ViewClock so it could be used for rect.intersect comparion for example?

**Comment by falzonv** [comment]
Hello,

*(Sorry for the delay answering, I am quite busy with my job this year...)*

Your analysis are correct @queria, to give a bit more details:
- The home screen (favorites + clock + gestures area) and the app drawer screen are two full-screen displays replacing each other during navigation, this is why the clock disappears when the app drawer is displayed.
- In older versions of Discreet Launcher, the clock was moving along with the favorites (if the clock was on top, it was pushed below favorites). This has been changed in ticket #131 as it was kind of confusing, and new clock positions were added (although not mentioned in the ticket, when the empty space was too small the clock was also cropped by other views which didn't look good).
- Since then (~1 year ago), the clock is always displayed on the home screen, possibly behind the favorites when:
  - The clock is on top in classic interface (screenshots in the initial post).
  - The clock is in the middle, the screen is small and many favorites are selected (so the panel extends up to the middle).
  - The clock is at the bottom in reversed interface.
  - The phone is in landscape mode.
  - Probably other use cases that I am not aware of...
- It is indeed intentional that the clock is left visible when, like you described, the favorites and clock are at different parts of the screen. The clock being sometimes still visible behind the favorites is of course not intentional, more of a side effect.
- The clock view indeed extends across the whole screen and the date and time positions are computed at drawing. I am not sure they can accurately be calculated elsewhere as some variables are defined only at drawing time.
However, following ticket #238, the date and time areas are now stored in ViewClock attributes "rect_date" and "rect_time" which looks like what you described.

Your idea of checking if the clock intersects with favorites would be indeed the ideal scenario but unfortunately it is not that easy to implement properly because:

1/ As stupid as it may look, I never found a reliable way to measure the height of the panel of the favorites. For some reasons, all the methods that should provide these information ("getHeight()", "getMinimumHeight()" and "getMeasuredHeight()") are always returning 0 even when the favorites are currently being displayed.
Since I needed this information to check if some settings could be enabled without the user losing menu access, I found a way to estimate it (see in the second part of the method "keepMenuAccessible()" in [ActivityMain.java](https://github.com/falzonv/discreet-launcher/blob/main/app/src/main/java/com/vincent_falzon/discreetlauncher/ActivityMain.java#L303)) but this is probably not so accurate because there are many parameters at play (for example a long app name will wrap and add a line with some padding).

2/ It will surely happens that for some users the end of the panel of favorites will be *in* the clock area, not above or below.
We have two options in this case: fully hide the clock although it may have been partially visible, or let it displayed although it will be partially behind the favorites (current situation).
If we go for the first option, as the end of the panel is not accurately known (see 1/ above), we may even hide the clock when it could have been fully visible!

This is probably more text than you expected for such a detail, but I wanted to document a bit why the clock is displayed like that and why it is not so simple to improve it.
Let's keep this ticket open for a couple of weeks as we may have some interesting ideas, but I would prefer not to introduce too much code complexity just to solve this (an easy workaround is to simply select another clock position).

Best regards.

**Comment by falzonv** [comment]
Hello,

I will close this ticket as it has been months and I haven't had a bright idea to solve this.
As I wrote, an easy workaround is to simply select another clock position.

Best regards.
