### ISSUE TITLE
Hard to see when adding apps to folders

### ISSUE THREAD

**Issue by Blank-1973** [falzonv/discreet-launcher#260]
I want an icon to appear next to the app name when adding an app to a folder

**Comment by falzonv** [comment]
Hello,

Thank you for your suggestion.
Unfortunately this is not possible with the default Android multi-choice dialog and I do not want to create a custom one because it is a lot of added code complexity and potential bugs that I won't have the time to manage now.

As a workaround, since v6.3.0 it is possible to add an app to a folder directly from the main app list (long press the app and select "Add to a folder"), and to remove an app directly from a folder (long press the app and select "Remove from folder xxx").

Best regards.
