### ISSUE TITLE
Change Folder Icons

### ISSUE THREAD

**Issue by butjer** [falzonv/discreet-launcher#269]
It would be great if we could change the icons for the folders in the favorites section

**Comment by falzonv** [comment]
Hello,

Thank your for the suggestion.
Actually this is something I tried in the past but it introduces too much code complexity for what I have the time to maintain, sorry.

It is possible to assign a custom color to each folder though (click the folder icon in the interface to manage folders), so that the icons look more different from each other.

Best regards.
