### ISSUE TITLE
Allow to set up multiple app drawers

### ISSUE THREAD

**Issue by Thewisem** [falzonv/discreet-launcher#27]
![Screenshot_20210415-141655](https://user-images.githubusercontent.com/74511929/114860925-42e84a00-9df5-11eb-8f30-d7346ba1d1a9.jpg)
I would like for this option to be there in discreet launcher. It would help in organising apps and making it easier for someone to find multiple apps of the same category

**Comment by falzonv** [comment]
Hello,

Thank you very much for your interest in the project and your suggestion!

It seems that the need is the same than ticket #22 about folders (that is, allow to organize similar apps together), so I will not implement both solutions in parallel.
For now, I have a preference for the folders option because the application is primarily designed for phones where it would probably look better with folders than multiple app drawers.
**=> Would folders be also ok for you?**

Also, as I wrote to @xi7, any of the two solutions will take some time to be implemented (they are equally complicated to manage internally and, even after the basics are developed, it will require many tests before working fine).

Best regards.

**Comment by Thewisem** [comment]
Meh its OK. I can understand the appeal to folders so its fine. And all the best for implementing any one of them or both of them. Its hard so I am only putting suggestions. I would reccomend trying to contact some devs of nova launcher as they might have an idea.
All the best from my side

**Comment by falzonv** [comment]
Hello,

Thank you for your understanding and kind support!
I am rather confident in being able to implement this folders feature, it will just take some time ;-)

To avoid confusions I will close this ticket but do not hesitate to add comments if needed or wished (either here or in ticket #22 which will stay opened).

> trying to contact some devs of nova launcher as they might have an idea

Hum, not sure they would agree to help because I see that folders in the drawer is one of their paid features!
But thank you for the idea, I will keep it in mind in case it is really too complicated :-)

Best regards.
