### ISSUE TITLE
[Feature Request] Set a different wallpaper for App drawer

### ISSUE THREAD

**Issue by jcperil** [falzonv/discreet-launcher#270]
The app drawer assumes the same wallpaper as that of the home screen. I wanted to use Arcticons Dark [icon pack] which look nice with a monochromatic dark wallpaper for the app drawer. But I would prefer to have a home screen wallpaper that is not monochromatic. Is there a way to implement this feature?

#### Home screen wallpaper

![Home screen](https://user-images.githubusercontent.com/89805719/215248726-f34994a5-2cac-4c4a-9076-2ea35f57c586.jpg)

#### App drawer wallpaper

![App drawer](https://user-images.githubusercontent.com/89805719/215250024-9af06a1f-680b-4d07-8f5a-27ccf4b83bd4.jpg)

**Comment by falzonv** [comment]
Hello,

Thank you for your interest in Discreet Launcher :-)
Although not technically impossible, this is not something I will implement because it would add too much code complexity and potential bugs for the limited time I now have to maintain this project, sorry...

(From a technical point of view, Discreet Launcher is like a regular app but with a transparent background so that the user's wallpaper is visible behind it. To use a custom wallpaper for the app drawer, it would be needed to re-implement more or less what Android is doing to manage the system wallpaper, but in my app for it to be standalone.)

Maybe you could try to add a very small bit of transparency in the app drawer background color?
It would break the monochromatic feel while still looking quite different than the home screen by being much much darker.

Best regards.

**Comment by jcperil** [comment]
> Maybe you could try to add a very small bit of transparency in the app drawer background color?
It would break the monochromatic feel while still looking quite different than the home screen by being much much darker.

This works. Thank you so much. :)

I guess I should have been specific about a plain dark wallpaper in the title instead of generalizing to any custom wallpaper. I too wouldn't want to see bugs in my favorite launcher.

**Comment by jcperil** [comment]
I have a minor issue. I would like to have #2A293B color code as the app drawer background. I don't know how to achieve this because the launcher settings does not accept values like 2A293B. What can I do?

![purply blue](https://user-images.githubusercontent.com/89805719/215278405-5d8944d3-07c9-4750-9a1c-e3ae41f3d7e8.jpg)

**Comment by jcperil** [comment]
I have a minor issue. I would like to have #2A293B color code as the app drawer background.

![purply blue](https://user-images.githubusercontent.com/89805719/215279518-0bfdd830-9c27-42ca-ab7a-ae3c4ed9bdf9.jpg)

I don't know how to achieve this. When I enter the value 2A293B in `Base` field, none of the two pointers move to the color 2A293B in the spectrum. Trying to find the point 2A293B manually is hard. When users enter a valid color code, is there a way to make the pointers move to the entered color code?

![color picker](https://user-images.githubusercontent.com/89805719/215279415-17851eb0-ccd4-4573-8658-303de00205b7.jpg)
