### ISSUE TITLE
tv remote

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#272]
![IMG_20230207_160929~01](https://user-images.githubusercontent.com/67331785/217569308-7696593f-4192-4aae-a826-00692b2165cc.jpg)

possible add visual feedback using android tv remote, moving arrow ?

I can't identify which app will open

**Comment by falzonv** [comment]
Hello,

Interesting, I didn't know Discreet Launcher could be installed on a TV :-)

Yes there should be a way to have visual feedback when an item is selected by the remote, I will have a look (may take some time as I know nothing yet about Android TV).

Best regards

**Comment by xi7** [comment]
phillips android tv or tv box will work too.
my remote is air mouse but move using keys is better

:)

**Comment by falzonv** [comment]
Hello @xi7,

It has been a long time but I am pleased to inform you that in new release v7.3.0 I was able to add visual feedback on many elements: apps, search, main menu button and entries, touch targets.
The interface to manage favorites is also working now (buttons fixed, added visual feedback on move arrows).
Although I could test only in an Android TV emulator, all of this should work on a real TV.

Some remarks after further tests in the emulator:
- Enabling the setting "Operation > Touch targets (accessibility)" allows to easily navigate between favorites and app drawer with the remote control
- Hidden apps work as expected, which may be useful if there are pre-installed bloatware apps
- Long press menu works as expected by long-pressing the OK button
- Color picker only works partially (color can be adjusted with #RRGGBB but not with sliders, transparency cannot be adjusted) but changing it would be too complex
- Folders do not seem really usable, but I will not work on it (most TVs have very few apps)
- Changelog do not seem really usable, but I will not work on it (not sure anyone use it even on mobile...)
- Export and import were not possible because there was no file manager in the emulator

This release has been published today, here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by xi7** [comment]
![PXL_20230513_133444336](https://github.com/falzonv/discreet-launcher/assets/67331785/6b054fda-fdc4-411f-b002-987e53fc6b8f)

tnks, working very good.

**Comment by xi7** [comment]
maybe u need swipe top or bottom will show all apps (using mouse),  go to config and set favorites always screen add all apps u need.
