### ISSUE TITLE
Web apps don't open since v2.5.1

### ISSUE THREAD

**Issue by johanbove** [falzonv/discreet-launcher#28]
Thank you for including the support for web apps. Really appreciate it. Until last update to 2.6.0 the web apps were opening fine. But in this version the web apps can be added, and show up in the application list, but when clicking the web app, nothing happens.

Added web apps using Brave Browser on Android 10.
Fairphone 3

Will check if the issue happens too when Firefox is default browser. I prefer not to have Chrome as default.

**Comment by falzonv** [comment]
Hello Johan,

Really sorry for this, I was about to contact you to ask if it was working for you because I received this morning a mail from a user telling web applications doesn't work for him as well.

After further checking, it was in fact introduced in v2.5.1 while fixing a bug found with Android 8 (but at the same time it introduced this bug which seems to be only with Android 9 or higher).

I am working on a corrective that will be implemented in v3.0.1 (v3.0.0 was pushed to F-Droid few minutes ago).

Again, I am sorry for the inconvenience...

Best regards.

**Comment by falzonv** [comment]
Ok, this is now corrected in v3.0.1 which has been pushed to the stores few minutes ago and the usual publishing delay is:

- 0 to 2 days for Google Play
- 4 to 8 days for F-Droid

*Note: I will leave this ticket opened until the release is effectively published on both stores.*

Unfortunately I do not have any good workaround because Android does not really allows to export web apps (it keeps all the useful information in an internal database).

If you do not have too many web apps, you could export the settings, uninstall v2.6.0, reinstall v2.4.0 (not v2.5.1!) still available on F-Droid and import the settings again. Unfortunately there is a high chance that the system cleans the internal database when uninstalling v2.6.0 so the imported shortcuts would be broken and need to be recreated... (but after re-creation they should open normally and you could upgrade directly to v3.0.1 when it is available)

Best regards.

**Comment by falzonv** [comment]
Hello,

This release being now available on F-Droid, I will close this ticket.
Feel free to add comments if needed ;-)

Best regards.
