### ISSUE TITLE
Wrong Icon for App

### ISSUE THREAD

**Issue by AnonemooseBear** [falzonv/discreet-launcher#287]
I am using v7.2.0 from fDroid. I've applied custom icons (MaterialOS) and I see that there is a small issue with the wrong icon being used for my dialer (phone) app. It is the same as the one used for my contacts and it shouldn't be. There are numerous dialer icons included in the pack. If I use the Android 9 default icons then there are no problems with mixed up icons.

There is no option to change an app icon individually (would love to see that), so I can't fix myself.

**Comment by falzonv** [comment]
Hello @AnonemooseBear,

Sorry for the late answer, I am very busy with my job these months and hadn't connected to GitHub since a long time...

As the default icons are working properly, the issue probably comes from the MaterialOS icon pack rather than Discreet Launcher.
The association between apps and icons is done in their file https://github.com/materialos/android-icon-pack/blob/master/app/src/main/res/xml/appfilter.xml, which is the file read by Discreet Launcher but on which I have no control.

Although not technically impossible, changing app icons individually is not something I plan to implement as it would add too much code complexity and potential bugs for the time I now have to maintain this project, sorry...

Best regards
