### ISSUE TITLE
12-hr clock, and a couple other requests...

### ISSUE THREAD

**Issue by drewski-00h** [falzonv/discreet-launcher#29]
I've been enjoying this app for a couple weeks now.  I would really like to see a couple features:

•12-hour clock
•Default to home screen, not favorites page when navigating.  For an example of the workflow: Open favorites page>open any app>hit home>main screen (not favorites).
•Widget support? 

Just as a suggestion, this app works great with auto wallpaper change apps, like Unsplash.

Thanks for your work!

**Comment by falzonv** [comment]
Hello,

Thank you very much for your feedback, I am glad your like the application!

> - 12-hour clock

=> Sure, it could be a new setting allowing to switch between 12-hour and 24-hour formats.
Do you think it would look better with or without the AM/PM? (for example, would you prefer to see "3:47 PM" or simply "3:47"?)

> - Default to home screen, not favorites page when navigating. For an example of the workflow: Open favorites page>open any app>hit home>main screen (not favorites).

=> This should already be solved since v3.0.0, did you have the occasion to test with the last version?
If it is still not working maybe you discovered a bug, let me know...

> - Widget support?

=> Sorry, widgets support is not planned for now. The mains reasons are that (a) it requires additional permissions and (b) the general idea of this launcher is to have an empty home screen showing only the wallpaper.

> this app works great with auto wallpaper change apps, like Unsplash

=> Thank you for the information, good to know :-)

Best regards.

**Comment by drewski-00h** [comment]
Thanks for the reply...

• I'd prefer a clock "with" AM/PM.  Is it possible to toggle it further (with and without), with a 12-hr clock?
• I switched from the Fdroid version to the Play store version, which solved the workflow issue.   I gladly purchased the app!

Thanks, again!

**Comment by falzonv** [comment]
Hello,

Yes it is possible to propose both options for the 12-hour clock, good idea!
I think it should look good with a selector having the three options:
- 24-hour
- 12-hour with AM/PM
- 12-hour without AM/PM

It will be part of the next release v3.2.0 on which I will start to work tomorrow. It should be ready around Monday or Tuesday (I also want to integrate the feature request from #26 in this same release).

\
Thank you very much for your support, highly appreciated!
If you have the occasion, feel free to also rate the application ;-)
*(a bonus of the Google Play version is that you will get updates much faster ; the F-Droid updates have almost 1-week delay due to the automatic publishing process which is quite long)*

Best regards.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that the new release v3.2.0 has been pushed to the stores few minutes ago!
The usual publishing delay is:

- 0 to 2 days for Google Play
- 4 to 8 days for F-Droid

*Note: I will leave this ticket opened until the release is effectively published on both stores.*

Best regards.

**Comment by falzonv** [comment]
Hello,

Since release v3.2.0 is now published on both stores I will close this ticket.
Feel free to add comments if needed.

Best regards.

**Comment by xi7** [comment]
why not show the seconds option?

**Comment by falzonv** [comment]
Because I do not want to have an update process running every second just for the clock.
Also, the goal of the launcher is to limit distractions on the home screen, constantly changing seconds would surely add one.
