### ISSUE TITLE
Provide option to change single app icon manually

### ISSUE THREAD

**Issue by dheeraj025** [falzonv/discreet-launcher#294]
After applying new icon pack.there are app for which icon pack dont have icons.
And i want to change those app icon with other icon from the same icon pack.
Discree launcher dont have option to change app icon manually while every other launcher have .
Pls look into this

**Comment by falzonv** [comment]
Hello,

As I wrote in tickets #112, #137, #162 and #231, I do not plan to work on customizable icon for each app as it would introduce too much code complexity and potential bugs, especially now that I have much less time to maintain this project.

With ticket #130 the possibility to combine two icon packs was added, and in #149 the possibility to globally color all icons not covered by icon packs was implemented for more complete coverage.
The ticket #203 also mentions the app IconPackStudio which allows to create custom icon packs. I made some adjustments to Discreet Launcher in order to be more compatible with this app but never got feedbacks if it worked.

> Discree launcher dont have option to change app icon manually **while every other launcher have**

Quite a big claim as there are many other launchers which do not have this option either, including the Android stock launcher.

Best regards.
