### ISSUE TITLE
Option to always display app drawer

### ISSUE THREAD

**Issue by janPasi** [falzonv/discreet-launcher#297]
Could you maybe add an option to always display app drawer without the need to swipe up on the home screen? I find that I have very little use for separate home screen (with clock, favorites and such) and would much prefer to directly be taken to the app drawer.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but, since the point of Discreet Launcher is to have an empty home screen, I do not plan to implement it.

Have you tried Keikai Launcher? (https://f-droid.org/en/packages/com.anpmech.launcher)
It starts directly on the app drawer so this may be exactly what you are looking for.

Best regards.
