### ISSUE TITLE
Fix issues when several applications are from the same package

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#3]
good launcher but need some improviment 

* favorite bar, after add camera show two camera when camera and gallery is the same package.

* the app is very small but need a lot of waste memory load

* add bar translucent notification
* add click and hold app go to appinfo

and let me know if you want a challenge ? :)

**Comment by falzonv** [comment]
Hello,

Thank you very much for your feedback and suggestions!

For better follow-up, I suggest we split them into four tickets:

  - *"favorite bar, after add camera show two camera when camera and gallery is the same package"*
    => we will keep this ticket #3 (it will be renamed)

  - *"the app is very small but need a lot of waste memory load"*
    => see new ticket #4

  - *"add bar translucent notification"*
    => see new ticket #5

  - *"add click and hold app go to appinfo"*
    => see new ticket #6

*"and let me know if you want a challenge ? :)"*
=> Haha why not, feel free to open a new ticket to explain what you have in mind ;-)

**Comment by falzonv** [comment]
Ok, so for this issue there will be a lot of text to explain what happens.
I was able to reproduce it in an emulator with "Google" and "Google Voice Search" which are using the same package.

- When the launcher is started for the first time, the favorites list is empty and the applications list is built
- The user opens the favorites selector and selects some applications, let say (s)he checks "Camera" from package "com.example.cameragallery" but not "Gallery" from the same package
- Package names of all the selected applications are stored in an internal file (a basic text file with one package name per line) from which the favorites applications list is built
- At this stage, everything is as it should be in the favorites panel (there is only one "Camera" icon)

Now the user wants to modify the favorites and opens the selector again.

- When doing this, the internal file is read to pre-check all the applications which are already in the favorites and **it is there that the issue appears**
- The dialog contains the complete applications list and the package name of each one is checked against the internal file to see if it should be pre-checked or not (in our case "Camera" was checked so "com.example.cameragallery" is in the file)
- When browsing the list, "Camera" will match and be pre-checked (good) but "Gallery" will also match and be pre-checked since it is the same package name (not good)
- The user applies his/her modification without seeing that "Gallery" was automatically added and now there are two icons associated with the same package name

Of course the solution is to store a bit more (or different) information in the internal file in order to distinguish applications with the same package name. It could be simply to add the display name along with the package name but I have to think if there is a more relevant/robust option (I will keep you updated).

Also, I am wondering if this "identical package names" situation does not create also an issue in the complete applications list.

**Could you please test from the complete applications list if both the "Camera" and "Gallery" icons are working as expected?** (that is, "Camera" opens the camera and "Gallery" opens the gallery ; an example of perhaps wrong behavior would be that "Gallery" opens the camera)
On my emulator "Google" and "Google Voice Search" are showing the same screen but this may be intended by Google to promote the voice search...

Waiting for the bug to be solved, a possible workaround for the double icon is to manually uncheck "Gallery" before clicking "Apply" when you edit the favorites.

Best regards.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/111189153-91a38980-8594-11eb-8244-d8437d719c79.mp4

add favorite, camera and gallery, show two camera and both open galley

**Comment by falzonv** [comment]
Ok thank you very much for the demo.

So we need to add something for the case where a single package present several entries points (here "Camera" and "Gallery").
I will think about a good way to do it and keep you updated.

**Comment by falzonv** [comment]
Hello,

I was able to resolve the issue in release v1.2.0 which has been pushed to GitHub few minutes ago.
This will probably take 4 to 5 days to be fully replicated in the applications repository.

Once it is there, could you please upgrade the application to test if your Camera and Gallery icons are working normally?

Best regards.

**Comment by xi7** [comment]
> Hello,
> 
> I was able to resolve the issue in release v1.2.0 which has been pushed to GitHub few minutes ago.
> This will probably take 4 to 5 days to be fully replicated in the applications repository.
> 
> Once it is there, could you please upgrade the application to test if your Camera and Gallery icons are working normally?
> 
> Best regards.

i cant download the apk file from playstore because show restrict my country, possible u update to fdroid ?

**Comment by falzonv** [comment]
Hello,

Please read my previous message, the update has already been pushed to GitHub for inclusion in F-Droid but usually it takes 4 to 5 days before the application is built by F-Droid and available in their store (see the examples of issues #1 and #2).

This is an automatic process managed by F-Droid and I can do nothing about it except waiting for it to complete.

Best regards.

**Comment by xi7** [comment]
v1.2.0 update working very good, camera / gallery with old android. perfectly.

**Comment by falzonv** [comment]
Great, thank you for the confirmation!
