### ISSUE TITLE
[BUG] renaming apps installed in both the work profile and the normal user breaks name

### ISSUE THREAD

**Issue by Shkzeen** [falzonv/discreet-launcher#302]
Renaming apps installed in both the work profile and the normal user will result in user's app name turning into a config line
video:

https://github.com/falzonv/discreet-launcher/assets/50447695/d5a120b0-be22-4a11-8615-09b1adb46e10

Thanks!

**Comment by falzonv** [comment]
Hello,

Thank you for the report, I will have a look.
Work profiles is probably the least tested part of Discreet Launcher because I don't have any devices with work profiles.

Best regards.

**Comment by Shkzeen** [comment]
To make a simple work profile you can use [Shelter](https://f-droid.org/packages/net.typeblog.shelter/), which sets up a simple work environment!
sincerely.

**Comment by Shkzeen** [comment]
I'd also suggest adding a small icon in the corner to identify work apps, and making them grayed-out when work profile is disabled.
sincerely.

**Comment by falzonv** [comment]
Interesting, I didn't know about Shelter and will have a look, thank you for the tip.

**Comment by falzonv** [comment]
Hello @Shkzeen,

Sorry for the very very long delay...
Without entering in the details, since almost one year now I have repetitive strain injuries in both wrists and had to reduce a lot my computer activities, especially programming.

Regarding this ticket, I finally found what was wrong with the renaming and the fix is implemented in new release v7.6.0.
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards
