### ISSUE TITLE
Some icons not showing after device reboot

### ISSUE THREAD

**Issue by oneofmanyacdcfanstoo** [falzonv/discreet-launcher#303]
When I reboot my tablet (a WhoopConnect TAB8-US2), two of my most recently installed apps seem to be missing (Fennec F-Droid and F-Droid Basic). The first time this happened was right after the update to 7.3.0 and I was stymied; I thought those apps had been somehow lost so I set about to redownload them. Upon going back to the launcher several minutes later, I discovered they were back again. I rebooted the device again, and they were gone again. So I went into the app and hit "refresh the list of apps" which brought them back again and solved the problem. Can you add something where the app list is refreshed once more, or delay the timing of it? | think that should solve the problem. By the way, the two missing apps are gone from both the app drawer and the favorites/quick launch when the device starts up. 

I have not tried 7.3.1 yet because it hasn't pushed to F-Droid, but nothing about this was in the cgangelog. Thank you for reading my bug report. I really love this software, thank you for making it free and open source!

**Comment by oneofmanyacdcfanstoo** [comment]
So I just got the update in f-droid and the problem still exists.

**Comment by falzonv** [comment]
Hello,

Thank you for the report and sorry for my late answer, I am very busy with my job these months.

It is a very strange bug and to be honest I have no idea of what the reason could be, especially since I also have Fennec F-Droid on my phone and never observed any issue about it (just rebooted right now to be sure and it's there as expected).

Here are some questions to try understanding the issue better:
- Which version of Android are you using?
- Reading your message, I understand the issue started just after the update of Discreet Launcher to v7.3.0.
Do you know (even approximately) which version of Discreet Launcher you had before?
- Are the two icons disappearing from the favorites, from the app drawer, or both? (or maybe Fenned F-Droid is favorited but not F-Droid Basic?)

Note: if you want to rollback to an older version of Discreet Launcher, you can use the export/import feature to retrieve your configuration. F-Droid will display only the last 3 versions but all versions are available in GitHub (https://github.com/falzonv/discreet-launcher/releases).

Best regards.

**Comment by oneofmanyacdcfanstoo** [comment]
Sorry I didn't respond sooner. My tablet broke and I had to get a new one. I just downloaded your new version and everything seems to be fine. I think my problem may have been related to using an SD card as internal storage before, because that made everything load slower. Things are okay now so I will close the issue.
