### ISSUE TITLE
[feature/improvement request] Add 2 gestures: Swipe with three fingers up and down

### ISSUE THREAD

**Issue by devsantoss** [falzonv/discreet-launcher#310]
Hi @falzonv, I really like your launcher, I read your guidelines and I know you don't want to have code-related Pull Requests but I implemented this and I actually love adding these gestures a lot more! So I would like you to see if it is possible to add it. I've been testing this improvement and it has no drawbacks. 
Let me know if we can do this.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion and your interest in Discreet Launcher!
*(and sorry for my late answer, I am very busy with my job these months)*

Unfortunately, as I just announced in ticket [#314](https://github.com/falzonv/discreet-launcher/issues/314), no more new features or options will be implemented in Discreet Launcher.
Only maintenance releases to fix bugs and maintain compatibility with new Android versions will continue.

For info, I also wrote in the above ticket that it's ok for me if someone wants to create and maintain a more active fork and publish it to F-Droid and Google Play as long as it is properly rebranded to avoid confusion. But this is of course a much higher commitment than a pull request, I mention it because you already fiddled a bit with Discreet Launcher code and may be interested but please do not feel obligated in any way (I don't mind if there is no fork).

Best regards.
