### ISSUE TITLE
7.4.0 constantly showing “List of apps refreshed” message on top of everything

### ISSUE THREAD

**Issue by unclechu** [falzonv/discreet-launcher#316]
Recently I updated from 7.3.1 to 7.4.0 on F-Droid and the app is constantly showing “List of apps refreshed” message at the bottom of the screen with the app’s icon. The intervals are not always clear. Sometimes it’s just a couple of seconds, sometimes it’s 10 seconds. The message is shown on top of any other application. You can watch a video fullscreen and you will see these messages constantly interfering.

Android 13, OnePlus 9 (LE2113).

**Comment by unclechu** [comment]
![1000002761](https://github.com/falzonv/discreet-launcher/assets/799353/6873ebad-5029-48bf-a8bc-eb6067f550fa)

**Comment by unclechu** [comment]
Also I noticed that the app consumes a lot of energy now. It’s in the top 3 battery consumers for me now.

**Comment by kflak** [comment]
Can confirm the same behavior on my Mi A4 running Android 11. Battery usage seems normal, but I am getting the "List of apps refreshed" message all the time.

Thanks for a great launcher, btw, @falzonv!

**Comment by falzonv** [comment]
Hello,

Thank you all for the reports, this is probably related to #311.
I will make a rollback and publish a new release.

Best regards.

**Comment by kflak** [comment]
Great, thanks!

**Comment by falzonv** [comment]
Hello,

It should be fixed in new release v7.4.1, sorry for the inconvenience!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Hello,

The F-Droid version is available since one week and, as far as I know, the bug is not present anymore.

Best regards.
