### ISSUE TITLE
Seach field takes unlimited input

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#321]
If leaving the phone in the pocket or resting something on it,
it is possible that a lot of letters get typed in the search field.
This poses a problem, because it can't be selected all at once to remove it.
Instead it means having to stay on the backspace till it is all gone.

Maybe limit the available input to the length of the field, so it doesn't scroll?

**Comment by falzonv** [comment]
Hello,

Thank you for the report, I hadn't thought about this case.
Not sure if I can limit the input to the length of the field (depends on screen size and orientation), but I guess that a hard limit at 30 characters should be more than enough for all use cases.

A workaround is also to tap the empty part of the screen above the search field (where results would appear), it will close the search module and when opening it again the field will be empty.

Finally, I am really sorry for the late reply.
Since my announce in https://github.com/falzonv/discreet-launcher/issues/314 (maintenance mode), I now also have computer-related health issues (repetitive strain injuries in both wrists) and had to reduce a lot my computer activities, especially programming which includes Discreet Launcher.
Now it is going a bit better (thanks to a combination of reducing activities, having better ergonomics, using [Workrave](https://github.com/rcaelers/workrave) at work and at home, and seeing a hand therapist) but I honestly still feel quite far from a full recovery...

Best regards

**Comment by falzonv** [comment]
Hello,

For info, this has been solved in new release v7.5.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.
