### ISSUE TITLE
Icon pack: Folder icon always turns white

### ISSUE THREAD

**Issue by Npepperlinux** [falzonv/discreet-launcher#336]
All folder icons are monochromatic white when the icon pack corresponding to Discreet Launcher is applied (Arcticons are white line icons so I can't find this problem).
I think it is related to the color filter setting for each folder icon.

| Arcticons | Arcticon White(black-line) | Arcticons Material You | Delta |
| :-: | :-: | :-: | :-: |
|![discreet-launcher_with_arcticons](https://github.com/user-attachments/assets/6d4d9812-a94e-46b5-b42c-f4a2ab6ca237)|![discreet-launcher_with_arction-black](https://github.com/user-attachments/assets/a2160b78-abdc-4f51-9a4e-fd6717428b2c)|![discreet-launcher_with_arcticons-material-you](https://github.com/user-attachments/assets/d952bc55-6925-44d0-b979-ec10460cd20f)|![discreet-launcher_with_delta](https://github.com/user-attachments/assets/08f934e4-ceab-4467-afaa-3ec1ba5262a9)|

**Comment by falzonv** [comment]
Hello,

Thank you for the report and screenshots!
It is in fact related to the recent PR https://github.com/falzonv/discreet-launcher/pull/322 and I am not sure how to manage this.

Each Discreet Launcher folder has a user-defined color applied on its base icon and app count (by default this is white, it can be edited by clicking the folder icon in the "Folders" menu entry).
So regardless of the icon color in the icon pack, the final result will be of the color defined in Discreet Launcher (white by default, but it could be any #RRGGBB and also supports transparency).

For the second screenshot you can fix it by changing the color for the "settings" folder to black.
@Donnnno: on the 2 first screenshots, it seems the base icon is a bit too high for where the app count appears, could you adjust it?

For the last 2 screenshots it's a bit more complicated, you can define a more fitting color (that will look better with other icons around) but since there is no "hole" in the icon for letting the app count appear it will be blend with the base icon.
@Donnnno, @GitGitro:
Would it be possible to insert a transparent part in these base icons so that the app count could appear?
I am not sure how to compute the position where the app count would appear in the icon XML, it is meant to be integrated in the |\_\_| shape at the bottom of the [Discreet Launcher icon](https://github.com/falzonv/discreet-launcher/blob/main/app/src/main/res/drawable/icon_folder.xml) that you can see in the screenshot below (this |__| shape is large enough to fit a 2-digit number with the same gap size with the sides and bottom lines).

<img width="200px" src="https://private-user-images.githubusercontent.com/89805719/289383262-cfd6be79-519a-49a3-bd38-b4927da11b74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzczNzIsIm5iZiI6MTcyMzIzNzA3MiwicGF0aCI6Ii84OTgwNTcxOS8yODkzODMyNjItY2ZkNmJlNzktNTE5YS00OWEzLWJkMzgtYjQ5MjdkYTExYjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIwNTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYzUzY2E3Y2M5NDA0M2Y4NjJkM2RiZTA5MjVjM2QxMDA4YTg5ZjdmZTU2MjI4ZDAzNGY0ZjJmMTVjYzY1YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QbSbMLUJLFh5nvr7oCytGoGhHrVcOCvFISTB95tTNAE"/>

Sorry guys for the inconveniences, I never thought when implementing folders 3 years ago that someday we would try to integrate them with icon packs...

Best regards

**Comment by kaanelloed** [comment]
That's on me, I didn't explain the reasoning behind my [commit](https://github.com/falzonv/discreet-launcher/pull/322/commits/2493aeb467fdc4ddce4df6b185dff8bebc6085f8) and didn't follow-up.

This is why I originally wanted the icon pack to manage numbers by creating icons for each of them. This way, the launcher doesn't have to manage the colors, and the number is consistent with the style of the rest of the icon.

**Comment by falzonv** [comment]
Reopening, it's a bit annoying that GitHub silently close tickets when PR are merged.

However this is the occasion to inform you that, thanks to the work of @kaanelloed, this issue will soon be solved with no actions required for users or icon pack maintainers :-)

I plan to publish the release this week and will close this ticket once the new release is available on F-Droid.

**Comment by falzonv** [comment]
Hello,

Actually the new release v7.7.0 has been published few minutes ago!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by GitGitro** [comment]
Hi, sorry for the lack of response, it totally slipped with the other emails.
Thank you for your work @kaanelloed!

I'll test asap with Delta and report back
