### ISSUE TITLE
Propose 2nd arrangement with favorites at bottom

### ISSUE THREAD

**Issue by tuch96** [falzonv/discreet-launcher#42]
Hej Vincent!

I have 2 new suggestions for the favourites menu.

1. A flexible arrangement of the icons within the favourites. During daily use, I noticed that the icons that are called up most often should be placed as close to your navigate finger as possible. In other words, prioritisation.

2. A flexible arrangement of the favourites menu. In addition to the arrangement at the top of the screen, an arrangement at the bottom or right edge of the screen would also be great. In this way, everyone can find out for themselves which menu position is easiest. I have also attached a few screenshots of suggestions for this.

What do you think?

![Screenshot_20210511-153152_Discreet_Launcher1](https://user-images.githubusercontent.com/57192210/117827867-a1c4a600-b271-11eb-9bec-5c4b703440d2.png)
![Screenshot_20210511-153152_Discreet_Launcher2](https://user-images.githubusercontent.com/57192210/117827949-b5700c80-b271-11eb-9e45-c448c5ebc265.png)

**Comment by tuch96** [comment]
Hej Vincent,



> Hello!
> 
> Thank you for your suggestions and screenshots :-)
> 
> > 1/ A flexible arrangement of the icons within the favourites. During daily use, I noticed that the icons that are called up most often should be placed as close to your navigate finger as possible. In other words, prioritisation.
> 
> => Do you mean that the user should be able to select manually the order of favorites, or that they should reorder themselves based on usage frequency? (currently they are ordered alphabetically, with folders first starting with v3.4.0)
> 
Yes, I meant the manual arrangement without the usage frequency. Then there is no need for data tracking :-)

> The first case (manual order) may be possible, probably not so simple but I would have to look.
Perfect!!

> > 2/ A flexible arrangement of the favourites menu. In addition to the arrangement at the top of the screen, an arrangement at the bottom or right edge of the screen would also be great. In this way, everyone can find out for themselves which menu position is easiest. I have also attached a few screenshots of suggestions for this.
> 
> => Not tried yet but proposing a second arrangement with favorites at the bottom should be possible :-)
> However, it would have to be an inverted mode, with the favorites opening from the bottom with swipe up (as in your first screenshot) and the drawer opening from top with swipe down (otherwise both swipe up actions would conflict, and continuing to open the favorites with swipe down would be counter-intuitive if they appear at the bottom).
> => Would this still be ok for you?
> 
I only use on my Pixel phone the gesture control. Currently, a swipe from the bottom opens the main app overview. This could possibly also cause a conflict if it is used at the same time as opening the favourites menu. It depends on where the swipe has to start. If you start a little higher on the screen and then swipe upwards, it might work. Can this distance be stored in the code? Or is there also the possibility to start a swipe from the middle? Middle up or middle down to open the menu?

If that doesn't work, a double function with only a swipe from the top to opening on the top or bottom would be ok from my point of view! From the point of usability it is a quick learning step.

> Regarding bottom vs right for a second arrangement, I am more in favor of favorites at the bottom as it would be more universal (regarding left-handed people) and keep the navigation logic simple with only up/down (a menu on any edge would mix up/down for drawer and left/right for favorites, it may also be somewhat random if the user swipes diagonally).
> 

I agree with that. Top and bottom... that's enough.

Good night :-)!

**Comment by falzonv** [comment]
Hello,

Regarding the manual sort of favorites, I created separate ticket #44 for follow-up (will probably take some time).

For the favorites at bottom, we used so many times the words swipe, up, down, top and bottom in our sentences that I am a bit lost in what you explained to be honest :-)

> I only use on my Pixel phone the gesture control. Currently, a swipe from the bottom opens the main app overview. This could possibly also cause a conflict if it is used at the same time as opening the favourites menu.

=> Not sure to understand where the conflict would be, here is the current behavior regarding swipes from the home screen:

- Swipe going down:
  - Open the favorites menu
- Swipe going up:
  - If the favorites menu is opened, close it to have empty home screen.
  - If the menu is already closed, open the complete applications list (drawer), is this what you mean with "main app overview"?

Since you cannot swipe going up and going down at the same time, there should be no conflict.
Or am I missing something?

>  It depends on where the swipe has to start.

=> Currently, you can swipe from anywhere you want on the space not taken by the menu, only the direction (up or down) and a minimal distance (to ignore simple taps) matter for the behavior described above.
*(so if the distance is enough, you can start the swipe down to open favorites from almost the bottom of the screen, and the other way around for the applications list)*

Maybe it was not really clear in my previous message, I probably shouldn't have said "from top" or "from bottom".
Here is how the navigation would be with the "inverted mode" I suggested (just inverting up/down compared to the above).

- Swipe going up:
  - Open the favorites menu
- Swipe going down:
  - If the favorites menu is opened, close it to have empty home screen.
  - If the menu is already closed, open the complete applications list (drawer), is this what you mean with "main app overview"?

> If you start a little higher on the screen from the bottom and then swipe upwards, it might work. Can this distance be stored in the code? Or is there also the possibility to start a swipe from the middle? Middle up or middle down to open the menu?

=> Yes, it could be possible to take into account the point where the swipe started to see if it is in the first half or the second half of the screen. So you mean that if the user swipes up in the lower half of the screen it would open the favorites, and if (s)he swipes up in the higher half of the screen it would open the complete list?

However, I think that it would be simpler to have a navigation like I described above (would be the exact opposite of the standard arrangement) which doesn't rely on the starting point position but only the direction.

> If that doesn't work, a **double function with only a swipe from the top to opening on the top or bottom** would be ok from my point of view! From the point of usability it is a quick learning step.

=> Here you lost me, sorry could you try to rephrase it? :-)

Best regards.

**Comment by tuch96** [comment]
Hej Vincent!

A lot of swipes... :-)).

> Here is how the navigation would be with the "inverted mode" I suggested (just inverting up/down compared to the above).
> 
>     * Swipe going up:
>       
>       * Open the favorites menu
> 
>     * Swipe going down:
>       
>       * If the favorites menu is opened, close it to have empty home screen.
>       * If the menu is already closed, open the complete applications list (drawer), is this what you mean with "main app overview"?
> 

That's exactly what I meant. It was late at night and I described it too complicated - sorry ;-).

I think your suggestion for navigation is good. Let's give it a try!!

Good night!

**Comment by falzonv** [comment]
Hello,

Since it was only about inversions, it was quicker than I thought and I am pleased to inform you that this will be part of new release v3.5.0 which has been published few minutes ago!

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by tuch96** [comment]
Hi Vincent! Great job and thanks for the info. But one questions. The function to place the favorites menu bar to the bottom (see my first screenshot) you will released it in the next version? Kind regards!!

**Comment by falzonv** [comment]
Thank you!

I confirm the layout of your first screenshot is available in the next release v3.5.0 mentioned in my previous message :-)
More precisely, you will find this option at "Settings > Display > (Home screen section) > Reverse interface".

**Comment by tuch96** [comment]
To many swipes in this area :-)))!!! Now I have seen it too. Vincent...a perfect implementation on the bottom. And it works brilliantly. Thanks for your support!!

**Comment by falzonv** [comment]
Thank you very much for your kind words!
I am glad to have supportive users like you :-)

**Comment by falzonv** [comment]
Since v3.5.0 is now available on F-Droid since yesterday, I will close this ticket.
