### ISSUE TITLE
Double tap to sleep

### ISSUE THREAD

**Issue by KaiFujiro** [falzonv/discreet-launcher#48]
hello can you add the double tap to sleep feature? I used to try the Xperia launcher (Port app) there was a feature like that. is it possible to add it in this launcher?
Thanks

**Comment by falzonv** [comment]
Hello,

Not sure if this will be possible, at first look it seems to require some admin permission to turn off the screen and put the phone to sleep. I will check if there are some other ways...

In case there is no other way than with these permissions, then it will not be implemented because I want to limit permissions to only what is strictly mandatory (by the way, if these are really admin permissions, they may not even be accessible for third party apps, only for system and vendors/manufacturers).
Currently, the only permission requested by Discreet Launcher is QUERY_ALL_PACKAGES (for obvious reasons).

Best regards.

**Comment by tuch96** [comment]
> In case there is no other way than with these permissions, then it will not be implemented because I want to limit permissions to only what is strictly mandatory (by the way, if these are really admin permissions, they may not even be accessible for third party apps, only for system and vendors/manufacturers).

@falzonv No permissions... A very good decision for the future of this app!!

**Comment by falzonv** [comment]
Hello,

I come back to you after further investigation and indeed, a special admin permission is required to manage the device and put it into sleep mode. This is probably for security, as some bad apps could block the phone by putting it to sleep when opening the app (so when the user unlocks the app is shown again and it put the phone back in sleep mode, and so on).

Therefore I will not implement this feature.

By the way, while searching, I came across an app called "Easy Lock" which may interest you because it even has a mode "double tap to sleep from any application":
https://forum.xda-developers.com/t/app-4-0-material-easy-lock-double-tap-status-bar-nav-bar-to-sleep.3222024/

*Disclaimer: I have not tested this application (only looked at its [source code](https://github.com/aravindsagar/EasyLock) to check permissions and the way to go in sleep mode) and many users report that it doesn't work perfectly for them (for example after the phone is in sleep mode they cannot unlock with the fingerprint, have to use another method).*

Best regards.
