### ISSUE TITLE
Option to check for updates

### ISSUE THREAD

**Issue by KaiFujiro** [falzonv/discreet-launcher#54]
Can you add an option to check for updates automatically ?, like when we enter the launcher/when pressing the check update button.
So that I immediately know when there is an update

**Comment by falzonv** [comment]
Hello,

Sorry, this will not be implemented because I want the launcher to work completely offline.
This would also require additional permissions (see network connections, internet access, ...) that I do not want to request as they are not strictly necessary for the application core features.

If you want to be notified of updates, you should install the launcher via F-Droid or Google Play.
The F-Droid version is free but the publishing process is a bit long (usually 4 to 8 days after I sent the update), the Google Play version is paid but the publishing process is quicker (usually between a few hours and 2 days). Regarding features and source code, both are exactly the same.

APK files are provided only because several F-Droid users were too impatient for the publishing process, but then these users have to check themselves if there are new updates (or move back to the F-Droid version later).
=> This is why the recommended way to install the launcher is via one of the stores, it will manage updates checks for you.

Best regards.
