### ISSUE TITLE
[Feature request] Hide icon of notification in status bar

### ISSUE THREAD

**Issue by funnyflowerpot** [falzonv/discreet-launcher#58]
Hi Vincent,

First congrats to your lovely app and I really appreciate the very active and engaging collaboration here! This is exactly how I wished home screens would work and feel like.

My question in short: Is it possible to hide the icon in the status bar?

I like the feature of having a sticky notification for quick access to selected apps. However, it seems an icon for the notification is always visible in the status bar, when another app is open. Although I appreciate the Launcher and the icon very much, I would prefer to keep the status bar empty unless urgent. Visible notifications trigger FOMO stress in me ;-) and maybe I'm not alone in this.

In one or two other apps I have seen that is seems to be possible to have a sticky notification, but not having it show as icon. (Would need to look up which apps those were.) One of those apps seemed to use an icon that was completely transparent, but this might have been a hack on a rather old Android version. I'm using LineageOS, but I think this should not make a difference.

**Comment by falzonv** [comment]
Hello,

Thank you very much for the kind words and your feedback, and I am glad you like the launcher :-)

I totally agree with you that it would be better without the notification icon. Although the icon is not too bad, having it displayed in the status bar is something that I am also not very satisfied with.
There are very few mandatory things for a notification but unfortunately the icon is one of them...

> In one or two other apps I have seen that is seems to be possible to have a sticky notification, but not having it show as icon. (Would need to look up which apps those were.) One of those apps seemed to use an icon that was completely transparent, but this might have been a hack on a rather old Android version.

=> When creating the notification at the beginning, I also tried with a transparent icon but it was sometimes making a blank space between other notifications, depending on how they were arranged. It looked a bit buggy so I decided to stick to a real icon.

I just tried it again and when having other notifications they are shifted from one position to the right and there is an empty space at first (the transparent icon). If in this setup a new notification appears, it takes the first place and the empty space moves in second position and so on.

This looks a bit strange but, thinking about it again, people do not always have other notifications and maybe a possible invisible space is still better than a constant notification. What do you think about it?

> (Would need to look up which apps those were.)

=> Indeed, if you retrieve one of these apps and if it is open source, looking in the code how the developer(s) solved this could suggest other things to try.

---

By the way, trying to hide a bit the icon is the reason why I decided to hide the notification when on the home screen. If there was no icon the notification could always stay. It would avoid to create/destroy it each time and would be appreciated by users who start to get used to the notification (since it appears only outside of the home screen).

Now, saying this gives me another idea: if the notification is created when the launcher starts and always stays like described above, it may lower(\*) the chances to see the strange invisible space as the order seems based on last created.
*(\*) lower but probably not fully eliminate, for example if a user installs the launcher while having other notifications, (s)he will see all his/her notifications shifted from one position.*

Best regards.

**Comment by funnyflowerpot** [comment]
Whoa, thank you for the fast response!

> when having other notifications they are shifted from one position to the right and there is an empty space at first (the transparent icon).

Yes, this was how it was for one of the apps I had in mind. 

> This looks a bit strange but, thinking about it again, people do not always have other notifications and maybe a possible invisible space is still better than a constant notification. What do you think about it?

I agree it looks a bit weird, if one is not used to. I think having this option would be nice, although it's not a 100% perfect solution. Maybe some descriptive note ("for technical reasons" yada yada) in the settings helps.

> if the notification is created when the launcher starts and always stays like described above, it may lower(*) the chances to see the strange invisible space as the order seems based on last created.

Great point! That sounds like it could work. I think since this is mostly an issue of cosmetics, edge cases (like directly after installation or activation of this feature) could be respected with a note somewhere, but neglected otherwise.

That reminds me that I think in one of the apps I had in mind (the one which solved it a bit better) there were further options to fine-tune the placement of the notification (not limited to the icon). I never got into app development so far, but it sounded like there are some sort of priority that can be defined for a notification, and that priority is used by Android to sort notifications. It sounded like this goes beyond stickiness, but I'm not sure.

> => Indeed, if you retrieve one of these apps and if it is open source, looking in the code how the developer(s) solved this could suggest other things to try.

I will try! I can't promise really, as it's been a while and I can't really recall which ones had those features. But I'll have a look.

**Comment by funnyflowerpot** [comment]
>=> Indeed, if you retrieve one of these apps and if it is open source, looking in the code how the developer(s) solved this could suggest other things to try.

One of the apps is [Orgzly](https://github.com/orgzly/orgzly-android). In the setting there is a toggle button to have a "Ongoing" notification ("Quickly create new note or sync notebooks from notification drawer"). Below that there is a setting to select an "Ongoing priority", to choose from the options: Maximum, High, Default, Low, Minimum. 

When I select Minimum, no icon is visible, but a notification exists. The "Access to favorites" notification looks visually a bit different from Orgzly's notification (and another one). I assume this is to reflect a notification property like stickiness. Right now I can't tell whether there is no icon or a transparent icon, but I think in the past I did not notice empty spaces in the status bar, when it was full of icons.

The other app was on some older device. I can check that a bit later.

**Comment by xi7** [comment]
I think the icon is elegant, but is strange the white bar and access is not so quick for one hand scroll.

it would be more interesting to put an invisible side bar access by swipe command ?

**Comment by falzonv** [comment]
@funnyflowerpot:

Thank you very much for these information and your feedback :-)
You are right, the invisible space could simply be explained in the Help section.

Just tried to set the importance to Minimum but this has a bad side effect: the notification is displayed but not expanded, so the user needs to click two times on the notification to open the favorites popup (one click to expand, one click to open).
When setting importance to Low, the notification is properly expanded but the icon is visible.

After checking Orgzly repository, they do not use a transparent notification and it seems based only on the importance level. Since there is already a gesture to do before clicking the notification (that is, open the status bar), I will not use the Minimum level because it would add a second gesture to do (expand) and would become impractical.
However, using the Low level can help further to ensure that a transparent icon would be at the end of the bar.

**I will give a try to a "Low level notification with transparent icon created on start" in the next release :-)**

---

@xi7:
I tried to apply a background color to the notification but it was not working, it is something set by the system (on devices having a night theme, the notification is displayed with a black background instead of white).

Regarding a side bar access, there is the same issue than for the float: my application is not allowed to draw over other applications or replace their gestures (like swipe or drag) by its owns (this is also why there is a gray background that I cannot change around the notification popup, Android adds this to show the user that the popup is launched by another application).

> After further checking, adding the float would require the permission to draw over other applications.
Unfortunately, this permission is protected by Android and only the system itself or phone vendors can have it...
>
> >Extract from [Android documentation](https://developer.android.com/guide/topics/permissions/overview#special):
"Special permissions correspond to particular app operations. **Only the platform and OEMs can define special permissions.** Additionally, the platform and OEMs usually define special permissions when they want to protect access to particularly powerful actions, **such as drawing over other apps**."

**Comment by funnyflowerpot** [comment]
> I will give a try to a "Low level notification with transparent icon created on start" in the next release :-)

Awesome, thank you very much for taking the time to look into this! Looking forward to this!

An alternative might be to provide a checkbox in the settings to let the user choose between options. This spares you from making this decision where users might have opinions about. But really, just thinking out loud here, I think how you suggested it would be perfectly fine to me.

**Comment by falzonv** [comment]
After further tests I am a bit disappointed because it seems the transparent icon is always first in the list, so there is always an empty space before the first visible icon :-/

Setting the priority to Low doesn't seem to really make a difference, and creating the notification only one time at startup doesn't change anything either. I wonder if this could be related to being the launcher...

![2021-05-27_notification_1](https://user-images.githubusercontent.com/4698531/119895652-529f9600-bf3e-11eb-8c63-ba86a9bbd8b6.jpg)

Also there is a sort of alignment glitch with the title of the notification due to the icon being invisible. Not a really concerning issue but I had not noticed it previously.

![2021-05-27_notification_2](https://user-images.githubusercontent.com/4698531/119895664-56331d00-bf3e-11eb-882e-465dd7a9d44a.jpg)

I will continue to look for possible other ways. Even if it can be explained in the help, I would prefer to not have the empty space at the beginning of the bar (at the end would be better, but the order seems controlled by the Android system).

**Comment by funnyflowerpot** [comment]
Thanks for posting this update!

That's strange and a bit of a shame. I looked at the code briefly, but didn't have any insight unfortunately. I also thought with `setPriority()` and `setImportance()` (i.e. `NotificationChannel`'s constructor) things should be working. I will continue looking and get back, in case I find something.

Not sure whether this helps, but this is how it looks on my end with the current release.

![sc](https://user-images.githubusercontent.com/7620049/119968676-068c3a00-bfae-11eb-9baf-df4020fa6964.png)

**Comment by funnyflowerpot** [comment]
> Just tried to set the importance to Minimum but this has a bad side effect: the notification is displayed but not expanded, so the user needs to click two times on the notification to open the favorites popup (one click to expand, one click to open).
> When setting importance to Low, the notification is properly expanded but the icon is visible.

Thinking about it again, this seems to be true for the Orgzly Notification (lowest in the list in the screenshot above): I have to "pull down" the notification to see the two buttons I can then tap. This is not the case for the Syncthing notification. In both cases, I can tap without pulling down the notification and the app opens. In Orgzly's case, when tapping the notification (without pulling down), the form to enter a new note then appears. This is different from default screen presented by the app, when starting the app normally.

Based on this I would conclude that it is somehow possible to have some custom action being executed when tapping on the notification once. Not sure how difficult that is to implement though.

**Comment by falzonv** [comment]
Hello,

Thank you very much for these inputs!
With this and some other tests on my side with the Minimum importance, I now start to understand how it works:

- **Before Android 8**, the Minimum importance does exactly what we want: the notification icon is hidden in the status bar, the notification is still displayed and it is directly clickable.
  - The Discreet Launcher should appear like the Syncthing notification on your screenshot.
  - Looking at your tests, it seems to be the same on LineageOS (not sure how LineageOS versions are following or not Android versions ; since my current phone is not supported I never tried LineageOS).
  - Only special controls (like for Orgzly) are hidden and need an additional gesture to be displayed.
- **Starting with Android 8**, the Minimum importance also hides the icon and displays the notification, but it is collapsed.
  - You can see the difference by comparing the "USB charging" notifications in our respective screenshots, yours is shown entirely while mine is collapsed and needs one more click to be usable).
  - Another change with Android 8 is the introduction of Notification Channels:
    - Before Android 8, the importance was set on each notification with the ``setPriority()`` method.
    - Starting with Android 8, it is set at the creation of the channel. Once created, this channel persists even when upgrading the application, so maybe some of my tests with Low priority were biased (that is, the channel importance never really changed). I will have to check this again...

**Conclusions:**
- When defining Minimum importance for ``setPriority()``, it should do the trick for Android before 8 (and for your LineageOS).
- For newer Android versions, I still have to find a good way to manage this (doing further checks with Minimum/Low, ...).

Good, at least we are progressing :-)

Best regards.

**Comment by funnyflowerpot** [comment]
Thank you a lot for all the effort and the reporting all the details here!

This seems you have found at least a partial solution! :clap: The Android 8 and up situation is probably still a bit unsatisfactory. I wish I could provide more assistance here, but for lack of device and API knowledge I can't really well. 

For reference, my Android version is 6.0.1 and my phone is also a bit dated. :)

> Once created, this channel persists even when upgrading the application, so maybe some of my tests with Low priority were biased (that is, the channel importance never really changed). I will have to check this again...
>
> For newer Android versions, I still have to find a good way to manage this (doing further checks with Minimum/Low, ...).

Not sure whether this helps and you might have seen this already, but in the [API docs for `NotificationManager`](https://developer.android.com/reference/android/app/NotificationManager#createNotificationChannel(android.app.NotificationChannel)) I found the following info.

> `public void createNotificationChannel(NotificationChannel channel)`
>
> Creates a notification channel that notifications can be posted to. This can also be used to restore a deleted channel and **to update** an existing channel's name, description, group, and/or **importance**. 
>
> The name and description should only be changed if the locale changes or in response to the user renaming this channel. For example, if a user has a channel named 'Messages' and the user changes their locale, this channel's name should be updated with the translation of 'Messages' in the new locale.
>
> The **importance of an existing channel** will only be changed if the new importance is lower than the current value and the user has not altered any settings on this channel.
>
> The group [of] an existing channel will only be changed if the channel does not already belong to a group. All other fields are ignored for channels that already exist.

It seems that `createNotificationChannel()` should be able to update previously created channels, within limits. Also, there is `deleteNotificationChannel()` in the same class. Maybe this aids testing? Good luck!

**Comment by falzonv** [comment]
Hello,

Indeed it was when reading this part of the documentation that I understood my previous tests with Android 8+ may be wrong.
**After testing again with a different channel ID set to "Low", the icon is not shown first anymore in the status bar!**

Testing on my phone since yesterday evening with this "Low" channel and a transparent icon, it does almost perfectly what we want (the only notifications icons displayed past the transparent one were Red Moon and the Android debugger).

I made further tests with the transparent icon and the "Low" priority before Android 8 and this seems to work fine as well (my initial tests were mostly with Android 8 and 11, I only tried the "Minimum" priority with Android 5).

So the "Low" priority should work in most cases and the other could be explained by a note in the help or under the setting itself (something like "uses a transparent icon" could be good). The "Low" solves the issue of the collapsed notification faced with "Minimum", and I also managed to remove the notification header so there is no hole for the missing icon.

Therefore for the next release I will:

- Delete the currently existing channel and create a new one with a "Low" importance (updating the existing one will not work if the user already edited the setting manually)
- And then the following should now work as we want:
  > Low level notification with transparent icon created on start

Best regards.

**Comment by funnyflowerpot** [comment]
Woah, this sounds like a lot of good insight and progress! Very nice and well done!

I was to suggest that when in doubt there could be an option in the settings, where effectively the behaviour could be toggled between Low and Minimum priority (with a more user-friendly explanation). But it seems this is not even necessary anymore. Great! 

Looking very much forward to the next release! I will beta-test as soon as possible. :)

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that new release v4.0.0 has been published!
This is a major release which solves many tickets at the same time, including this one.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Since today release v4.0.1 is available on F-Droid so I will close this ticket.
Feel free to add comments if needed.

**Comment by funnyflowerpot** [comment]
Just did a quick test. Looks and works excellently, every part of the updates!

**Comment by falzonv** [comment]
Great!
Thank you for the confirmation and kind words :-)
