### ISSUE TITLE
Access menu button

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#59]
why not put the **access the menu** when click the discret icon ?

and add press back bottom close folder. (physical, virtual, awipe) the click out folder is strange

**Comment by falzonv** [comment]
> why not put the access the menu when click the discret icon ?

Because it is counter-intuitive and most users would never find the menu.

> and add press back bottom close folder. (physical, virtual, awipe) the click out folder is strange

It seems to be again a bug specific to Android 5, because press back works normally with other Android versions...
Next time I create an application it may start with Android 6, less problems :joy:

Just joking, I will have a look and try to solve this also for Android 5.
Thank you for the bug report and I will rename this ticket to keep it for the bug follow-up.

**Comment by xi7** [comment]
u can use the icon name, discreet settings. super intuitive and you will have a clear home notification.

**Comment by xi7** [comment]
the question of the intuitive is exaggerated for that case of access configs, i never see any launcher with menu above the notifications.

other thoughts,
- why use 2 favorites once you can swipe up and call the implemented notifications folder?
- and find a way to use everything you already have to reduce the code

**Comment by falzonv** [comment]
Ok, I created a separate ticket for the press back bug (see ticket #60) so we can keep this one to discuss about the menu.

> i never see any launcher with menu above the favorites

=> Me neither, but a direct access to all settings and features was something I missed in the previous launchers I used before creating this one. Also as a developer I use this menu a lot when testing features and settings.
By the way, something that I also never saw is a launcher using its icon in the applications list as settings button...

---

Regarding this menu button, I am thinking about replacing it with something more discreet like in the screenshots below (the "engine key" icon is an).
Do you think this would look better?

@AeOeAa, @tuch96, @drewski-00h, @funnyflowerpot, @KaiFujiro:
I would also be interested by your feedback on this new button suggestion, is it a good idea?

Seeing them side-to-side, for now I prefer the new button.

| Current (normal and reverse mode) | Proposed (normal and reverse mode) |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/4698531/119854286-3df8d900-bf11-11eb-8e7a-1378b1a89c13.jpg" height="480" width="288"/><br/><img src="https://user-images.githubusercontent.com/4698531/119855250-09d1e800-bf12-11eb-9b86-89ff6e42e66c.jpg" height="480" width="288"/> | <img src="https://user-images.githubusercontent.com/4698531/119854631-84e6ce80-bf11-11eb-80ce-42fbd8ab8012.jpg" height="480" width="288"/><br/><img src="https://user-images.githubusercontent.com/4698531/119855256-0c344200-bf12-11eb-92bf-30d60fe5b891.jpg" height="480" width="288"/> |

---

> why use 2 favorites once you can swipe up and call the implemented notifications folder?

=> Personally I use this favorites panel a lot, so I will certainly not remove from my own launcher a feature that I use daily!

But a good news for you is that in the next release, as per ticket #58 and the new transparent icon, the notification will not be hidden anymore when the user is on the home screen ;-)

---

> and find a way to use everything you already have to reduce the code

This is already the case for almost everything. For example, the exact same code portion is used to display the applications in the favorites menu, in the applications drawer, in the folders and in the notification popup.

For information, all my code and resources files only represents 10 % of the APK size. More than half of the file size is due to the AppCompat Android library and its dependencies, which is used for backward compatibility with older Android versions.
Even with this, the file size is around 1.1 MB which is quite lower than many Android applications...

**Comment by xi7** [comment]
i prefer current reverse and option hide it and accessing by icon

**Comment by tuch96** [comment]
> the question of the intuitive is exaggerated for that case of access configs, i never see any launcher with menu above the favorites.
> 

I agree with @xi7. The actual position of "Access the Menu" crashs a little bit the design. For me it is a normal way to press the app icon to open the config settings of an app. I had already made the suggestion once. I don't like the suggestion of the spanner icon.

**Comment by drewski-00h** [comment]
I like the proposed version with the icon better.  With my use, it saves a click depending on what I'm trying to do within the settings.  I suppose you could everyone happy and enable both, no?

If you're looking at drawer/menu, as well...I think something similar to this would look nice (with a tab on the favorites)
![test2](https://user-images.githubusercontent.com/83047636/119878310-9919d400-beef-11eb-8521-342614f606a9.jpg)
, with whichever icon is preferred.

**Comment by funnyflowerpot** [comment]
> i never see any launcher with menu above the favorites.

This is not necessarily a reason against it. An app does not need to force innovation, but other people not having done something yet should not be the only reason against it, I think.

Personally I don't mind whether the favourites are shown on top or the bottom. I think it's good to bear in mind that the screenshots do not present the whole (interactive) picture. Swiping up and swiping down both pull up and down a menu each. So the question is not whether a menu should come from below or above (as both is the case), but which menu should hold the favourites.

> Regarding this menu button, I am thinking about replacing it with something more discreet like in the screenshots below (the "engine key" icon is an).
> Do you think this would look better?

Personally, I like it better, as it expresses the same idea in a simpler way, I think. Minimalism might be in line with the style of the app, but I'm obviously arguing with some bias here. :')

> I suppose you could everyone happy and enable both, no?

From a usability perspective it probably makes sense to let users choose things like menu placement or the degree of visual minimalism. I'm always for having more options in the settings, although some people dislike that. (Also, having more options also requires more code to maintain.)

> a direct access to all settings and features was something I missed in the previous launchers I used before creating this one. 

Quick access to settings could also be included in the pop-up window showing the favourites, which is accessed by tapping the notification. I can see the possibility that this might be in your interest in that case. A button for settings attached to that window might work well with the design.

Other ways for accessing settings might be: Swiping left or right, although that might also be not very obvious. Or including a "virtual app" on top of the list of apps saying "Discreet Launcher Settings", when selecting favourites. (Not sure how much work that would be. I'm calling it "virtual app" for a lack of the proper name.)

> Also as a developer I use this menu a lot when testing features and settings.

I understand the interest here. But looking into the future, do you think this need will persist? (Not trying to argue for or against.)

> For me it is a normal way to press the app icon to open the config settings of an app.

I think it can be intuitive to get to the launcher app settings when tapping the launcher icon. I think it would be unintuitive to get the menu that currently appears, when pressing "Access the menu".

**Comment by falzonv** [comment]
Hello,

Thank you all for your feedback!

> **xi7:** access by the current method and access by the start icon, possibility hide the current one.
> **drewski-00h:** I suppose you could everyone happy and enable both, no?
> **funnyflowerpot:** From a usability perspective it probably makes sense to let users choose things like menu placement or the degree of visual minimalism.

=> Ok for me, you are right: it is better to offer both.
I think **xi7** gave a perfect summary of the solution I should try to implement: \"access by the current method and access by the start icon, possibility hide the current one\".

Please note that it will take some time because, for technical reasons, I cannot directly reuse the current menu for the launcher icon. This is because I attached an Android contextual menu to the current button, but in the code this will not work well with the application icon so I have to recreate a similar menu with my own code (instead of the Android menu).
=> Not really an issue but it will take a bit more time ;-)

---

> **drewski-00h:** I like the proposed version with the icon better.
> **funnyflowerpot:** Personally, I like it better, as it expresses the same idea in a simpler way, I think.

=> Agree with you, the menu button would look better if it was replaced with an icon (and as mentioned above, the user could completely hide it in the settings to keep only the menu access via the launcher icon).

Regarding the exact icon, I have to check again what is available in Android system icons (I am not very good at drawing icons :joy:), maybe there is a gear like in the screenshot of **drewski-00h** but previously the closest I found was the spanner.

> **tuch96:** I don't like the suggestion of the spanner icon.

=> Sorry then... :-/
However, you preferred to have only the future launcher icon menu and, once I managed to implement what we described above, it will be possible with a new setting to hide the menu button. So at the end it should work for you as well :-)

> **drewski-00h:** I think something similar to this would look nice (with a tab on the favorites)

=> Good idea, I like it also!
Not sure how to do it yet but I will definitely give it a try ;-)

---

> **tuch96:** For me it is a normal way to press the app icon to open the config settings of an app. I had already made the suggestion once.

Indeed, now I remember you suggested this in ticket #24:
*\"An additional solution could also be a menu button directly in the Favourites app overview. If the app icon of your app routes directly to the settings when clicked. Then you could remove the bottom line completely. But maybe that's not good for the app usability?!? What do you think?\"*

=> At the time, the suggestion was to replace the menu button with an app icon directly in the favorites panel. I declined it because it was taking a slot from the favorites and adding an icon that the user may not want to see in his/her favorites. But perhaps I misunderstood your suggestion, sorry in this case... :-/

=> Here the launcher/menu icon would be in the complete applications list but not displayed in the favorites panel (unless the user selects it as a favorite of course). This is also why I found it less intuitive than a visible menu button.

---

> **funnyflowerpot:** Personally I don't mind whether the favourites are shown on top or the bottom.

=> My mistake, maybe it was not clear in the way I presented the screenshots: the choice to have favorites on top or bottom is already let to the user ("reverse interface" option, ticket #42 for more details), the two screenshots were only to show the menu button in both situations.

> **funnyflowerpot:** Quick access to settings could also be included in the pop-up window showing the favourites, which is accessed by tapping the notification. I can see the possibility that this might be in your interest in that case. A button for settings attached to that window might work well with the design.

=> Indeed that could be an additional access, I will start by doing what was described above and will see if and how it could be integrated in the favorites popup.
By the way in the next release, clicking on the title from the favorites popup will open the window to manage favorites (as it is already the case with folders titles).

> > **falzonv:** Also as a developer I use this menu a lot when testing features and settings.
> **funnyflowerpot:** I understand the interest here. But looking into the future, do you think this need will persist?

=> Indeed, probably someday there will be less new developments and the focus could be more on maintenance and internal optimizations (will still requires to perform tests, but much less than when developing a new feature).
However, the app is now published for several months and users keep having (good) ideas for new features :-)

---

That's a quite long answer, if I forgot anything feel free to mention it ;-)

Best regards.

**Comment by funnyflowerpot** [comment]
This sounds all very good, thank you for your all your dedication!

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been implemented in new release v4.0.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/120902278-ccf2a900-c615-11eb-9f76-0e9e9cfe048e.mp4

v4.0 no work android 5 the launcher icon crash

**Comment by falzonv** [comment]
Thank you for the bug report!

After further investigation it crashes only when the launcher icon is clicked from inside a folder (when it is directly in the applications drawer or favorites panel, not in a folder, it seems to work normally).
I have created ticket #64 for follow-up.

**Comment by falzonv** [comment]
Since today release v4.0.1 is available on F-Droid so I will close this ticket.
Feel free to add comments if needed.
