### ISSUE TITLE
Feature Idea - expand swipe gestures

### ISSUE THREAD

**Issue by bob-u** [falzonv/discreet-launcher#73]
Currently there's swipe up or down.  How about expanding it so swipe up, down, left or right at different part of screen invoke different action such as listing different group of icons or even launching an app.

I'm using this launcher in a car therefore, I like to look at the screen as little as possible.  Actions attached to gestures would work well in such environment.

**Comment by tuch96** [comment]
Good idea! Especially opening apps via the swipe function would be great.

**Comment by falzonv** [comment]
Hello,

Thank you for your feedback and your interest in this project!

> **bob-u:** or even launching an app
> **tuch96:** Good idea! Especially opening apps via the swipe function would be great.

I will have to check but it should be possible to open an application when swiping left or right from the home screen :-)

With settings to select an application for each direction, the user could open 2 applications like this in addition to the usual navigation in the launcher (note also ticket #70 suggested by @tuch96 for easier use in a car).

My only worry is that the swipe result would be unclear if the user swipes diagonally, will see during the tests ;-)

> **bob-u:** How about expanding it so swipe up, down, left or right at different part of screen invoke different action such as listing different group of icons or even launching an app.

It is not planned to implement different actions based on the area where the user swipes (top right, top left, middle, etc.).

This is because I prefer to keep the navigation simple to use. For example, I appreciate that the up and down swipes can be done from anywhere on the screen, no need to even think about a specific area (and it will be the same for the left/right swipes mentioned above, if I manage to implement them).

Another reason is that it keeps the code a bit simpler to maintain for me, especially because the application works also landscape and we have added a reverse layout mode since ticket #42 (so with specific areas in all these configurations, there would be a lot of corners cases and strange bugs to manage).

---

Finally, regular contributors may have noticed that the rhythm of releases has decreased since May (before it was often 2 releases per week, now it is closer to one release every 2 weeks). This is related to changes in my "real" job causing me to have less time to work on the application than before.
Nothing to worry about, but this is good to mention as it means new features take more time than before to be implemented.

Best regards.

**Comment by bob-u** [comment]
I use your software installed on a 9" android head unit.  It only works in portrait and has screen area large enough to easily have,  three different touch zones. 

Unlike phone users who likely use thumb,  android head units are usually controlled with pointer finger where user has easy access to all areas of the screen with similar effort.

Just keeps us, car radio users in mind if it's not too much effort.  I certainly would not want scope creep to slow-down or derail development and do appreciate that you make the app available via f-droid and don't require excessive permissions.    The app makes the android car radio look uncluttered which is awesome!

**Comment by falzonv** [comment]
Interesting, I didn't know my application could be installed on head units, that's cool!
Most users, including myself, are using this launcher on smartphones with screen sizes from 4" to ~6" so for use in car I thought it was with a smartphone on a stand mount.

Regarding swipes, I will start by trying to add left and right to open user-defined applications and we will see how it goes.
I can make no promises to add different touch zones but I will think about it (putting aside the added code complexity to maintain, the solution also needs to be compatible with screens much smaller than 9").

---

By the way, a couple of weeks ago I came across [Pie Launcher](https://f-droid.org/en/packages/de.markusfisch.android.pielauncher/) which is mostly based on swipe gestures.
Since I am happy with my own launcher, I never really tried it but I found the idea quite novel and interesting.
You may already know it, but this conversation reminded me of this launcher and I guess that on a 9" screen you could really take great advantage of its swipes-based behavior.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that horizontal swipes can open apps in new release v5.1.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

I also made some tries with zone-based swipes but will not implement this as it adds too much code complexity.

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by tuch96** [comment]
Hi Vincent,

the new version is landing today on f-droid. The wipe function works great and is a perfect addition. Great work.

Best regards
Marc

**Comment by bob-u** [comment]
Swipe left/right works great.  This feature is really nice addition for an Android HU.

**Comment by falzonv** [comment]
Hello,

Thank you very much for your feedbacks :-)
I close this ticket then.

Best regards.
