### ISSUE TITLE
Cloned Discreet Launcher in Google Play

### ISSUE THREAD

**Issue by drewski-00h** [falzonv/discreet-launcher#76]
Should this app be reported?  It looks awfully close to your app!  I know the Discreet is open source, but it seems they could have at least picked a different name.

https://play.google.com/store/apps/details?id=com.tglt.launcher.discreet&hl=en_US

**Comment by falzonv** [comment]
Hello @drewski-00h,

Thank you for the report, it is indeed a copy of Discreet Launcher :-/
*(probably the version 3.6.0, because the menu button was changed in the following releases)*

I am not sure how to react because the guy added some other features so he may still have put a bit of effort in this copy (or maybe he just copied these features from others apps...). But indeed, the name could be different and the description is a copy-paste where he just replaced "-" characters with emojis.

Recently I read an [article](https://android-developers.googleblog.com/2021/04/updated-guidance-to-improve-your-app.html) telling that Google will be more strict about applications names starting in second half of 2021.
So this copy may soon be removed by Google itself as it doesn't follow the new naming rules.

If not, I will try to report it to Google, but reading some comments over Internet, it seems this is not always taken into account and can be quite time-consuming, pfft...

**Comment by drewski-00h** [comment]
That must be frustrating!  Hope it works out.

**Comment by xi7** [comment]
when i search i can't find the original, only the copy

**Comment by falzonv** [comment]
I just sent a mail to the guy, we will see how it goes.

---

> when i search i can't find the original, only the copy

Since the application is only in English and French (with default to English), I thought it was better to select countries having one of these as major language to not pollute users stores from other countries with an English application (I was also afraid to get bad reviews due to the language difference, but most people are not leaving reviews anyway...).

Obviously, the copier did not care and published the clone in all countries.

Maybe I should think less and also publish in all countries, what do you think?

**Comment by xi7** [comment]
![Screenshot_2021-06-27-07-46-36](https://user-images.githubusercontent.com/67331785/123541642-ede18200-d71b-11eb-9ef5-571fb3233214.png)

the package discreet launcher have 300kb of language, not possible enable or delete save size file ?

**Comment by falzonv** [comment]
No because most of these 300kb are taken by Android built-in strings which are translated in all languages, so this is not something I can control. Here is an example below with an extraction of the APK from v4.2.0.

The strings are ordered alphabetically so my strings are mixed with Android strings, but looking at all the translations columns and sizes of the scrollbars, you can easily see what is taking so much space...

![2021-06-27_resources](https://user-images.githubusercontent.com/4698531/123543145-7c222c00-d74d-11eb-8cfa-9d3da13a0156.png)

**Comment by falzonv** [comment]
> Recently I read an article telling that Google will be more strict about applications names starting in second half of 2021.
So this copy may soon be removed by Google itself as it doesn't follow the new naming rules.

=> Just checked again the link above and now it is removed.
By the way, the developer(?) had a bit more than 20 other apps with names not following the new rules (and probably also copy-pasted), now his/her account is empty.
