### ISSUE TITLE
option to disable app drawer?

### ISSUE THREAD

**Issue by frpst** [falzonv/discreet-launcher#79]
I have most of my apps in a few folders I keep in my favorites while hiding the rest. Looks a bit awkward when I (mostly accidentally) open the app drawer and it contains less or equal to the number of apps in my favorites. 

Perhaps there is some way of implementing the option to disable the app drawer without locking people out of the Discreet Launcher settings?

**Comment by falzonv** [comment]
Hello,

Thank you for your feedback!
Indeed, I haven't thought about this case before and can understand that it looks a bit strange.

You are spot on, the critical point is to make sure that the launcher menu always stays accessible.
At first thought, I see at least three ways to access the menu without the drawer:
- With the menu button if it is not hidden in the settings
- Having the Discreet Launcher icon in the favorites (either directly or inside a folder)
- Having the Search icon in the favorites, as it provides access to all applications

Since this is the most useful of the three, I would tend to favor the Search icon way (managing all the ways would probably be too far fetched and prone to corner cases bugs).
There could be a check on the home screen and if the Search icon is not in the favorites we enable back the drawer.
=> Would it work for you?

Best regards.

**Comment by falzonv** [comment]
Hum, after second thought it is not reliable with the Search because its icon can be hidden.
Then the safest way would be to ensure that the Discreet Launcher icon is in the favorites (either directly or via a folder in favorites).
=> Would it work for you?

**Comment by frpst** [comment]
Definitely. I think ensuring that the DL icon is in the favorites is a nice solution. Thanks for your answer and solving my problem! :)

**Comment by falzonv** [comment]
Great, I add it to the list then :-)

**Comment by xi7** [comment]
I think the code should be reduced to maximum efficiency of use without too many options.

house main_folder_drawer at notificarion bar can be the same that old drawer by swipe up/down and also can be used like the search too.

**Comment by falzonv** [comment]
Thank you for the suggestion.
I do not plan to remove the app drawer because this is something I use myself everyday, and it is also the internal entry point for almost everything else in the launcher (favorites are picked from the drawer, folders are managed in the drawer, search is fully based on the drawer content, etc.).

When this option will be added it will allow to hide the drawer from user interface, but it is still needed for internal operation.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been implemented in new release v4.6.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

**Other good news:** I was finally able to implement checks for all the cases mentioned in my first comment. It means for example that, if the menu button is visible, there is no need to have the Discreet Launcher icon in favorites.
In case the user makes a combination of settings which would cause the menu access to disappear, the app drawer is automatically enabled back to prevent that (a short popup is displayed when this happens).

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by frpst** [comment]
Wow, thanks! Good job. Locking forward to it.

**Comment by falzonv** [comment]
I will close this ticket since v4.6.1 is now available on F-Droid (v4.6.0 was skipped).
