### ISSUE TITLE
With only icons, show pop-up name on touch

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#81]
add intelligence code effect while only icons scenery and hide until name folders

https://user-images.githubusercontent.com/67331785/124105266-71131880-da39-11eb-82c8-828606073251.mp4

**show pop-up name when touch/slide between icons**

**Comment by falzonv** [comment]
Hello @xi7,

Thank you for the suggestion!

I will have a look and try, but your video will probably not be exactly reproducible on a smartphone:
On a computer, the mouse can be over something without clicking on it, these actions are really dissociated.
With a smartphone, the finger needs to touch the screen before anything can happen and this is usually detected as a click, a long click or a swipe (which are all already affected actions).

Added to the list and we will see what is possible to do ;-)

Best regards.

**Comment by xi7** [comment]
combined hold and slide touch you can be reproducible smartphone ?

**Comment by xi7** [comment]
simple idea with double click = expand icon with pop-up name but not load, show only the effect.

or hold slide while slide between icons show effect like the video.

**Comment by xi7** [comment]
click show pop-up name and hold while slide showing apps name.
and maybe bump icon effect

**Comment by falzonv** [comment]
Hello,

After further tries, I face only issues with this (more details below if interested) and will not continue to work on it.
It adds a lot of complexity and doesn't even look good at the end, I am not able to reproduce this Apple effect on Android.

*Remark: if you need to check the name of an app before deciding to launch it or not, you can do a long click on this app and the first entry of the menu will tell you its name (then dismissing the menu will not launch the app).*

Best regards.

---

**More details**

1/ First, there is a functional issue due to the behavior difference between a computer and a smartphone:

=> On a computer, you can put the mouse over something for any length of time: as long as you don't press the click button of the mouse, no click will happen.

=> On a smartphone, when the finger stays too long on something it triggers the long click (which is the expected behavior).
Because of this, the app name is displayed only for a short length of time (start when the user touches the icon, end when the long click is triggered) so it is not convenient to read. It is even more difficult to read because, in a natural touch position, the user will have his/her finger tip on the icon and the rest of his/her finger will hide a part of the name (on a computer this problem is not present because the mouse icon is very small and stays only on the icon).

Some possible ways to workaround this would be to disable the long click, or to force a double click to launch the app but both are regressions in the usability of the launcher and I don't want to implement them.

I have not tried the hold and slide, it may make things a bit easier but will not solve the other issues (and the user will still have his/her finger in the middle hiding app names).
This would also require to constantly move to another app before the long click is triggered, which is not very convenient.

\
2/ The margins of the grid view are automatically all configured to the same size.
As a consequence, the bump effect is not possible because it would require different and variable values for each margins (but I don't control the margins, there are automatically set based on the number of columns).

Even if it was possible, it would not work with the "no margins" option (no room to do the bump effect as there is no margins).
And it would also add a lot of computations and complexity in the code just for a visual effect, this is not good either.

\
3/ When using the "no margin" option, the width to display the name is limited to the icon width (because all the columns of the grid view have the same size and there are no margins).
It means that most app names would be displayed on several lines with any word a bit long cut in the middle. This doesn't look good and, combined with 1/, make the displayed name almost unusable (difficult to read and displayed for a very short time).

I also tried to use a popup to display the name "over" the grid view but in folders and search it crashes the app (this is because they are PopupWindow objects and Android doesn't allow to display a PopupWindow from another PopupWindow).

\
4/ Having the app name appearing also temporarily create an horizontal space in the layout (to display the name on its line).
This is not really an issue by itself, but when the user just wants to click or long-click an app it makes a part of the layout "jump" (all apps below the clicked one go down for a moment and then come back up) which doesn't look good.

Same remark with the popup than in 3/, it could solves this point in theory but makes the app crash in search and folders.

\
I think there were other things (don't remember which), but the above is enough for me to say it will not be implemented.
Even if we found workarounds for all this problems, it would add too much complexity for just a visual effect (if the user really needs app names, (s)he can simply disable the "no app names" setting).

**Comment by xi7** [comment]
and what about: 

1 - after hold invert icon to text name just the app selected

2 - double click - enable/disable layout names

3- eyes icon by side tools menu in favorites, enable/disable

**Comment by falzonv** [comment]
> 1 - after hold invert icon to text name just the app selected

Interesting idea but this is not possible because the place of the icon can only receive an icon, not a text.
An alternative could be to create an icon of the text, copy the current app icon and replace it with the created text-icon, and a few moments after restore the app icon. But I will not do that, this would be a lot of complexity and resources waste.

> 2 - double click - enable/disable layout names
> 3 - eyes icon by side tools menu in favorites, enable/disable

No, I don't plan to add new menu/buttons in the interface or to manage double clicks.

---

The "no app names" option does exactly what it says: it hides all app names.
If you really need app names, then you should disable this option.
