### ISSUE TITLE
Simplify the app menu (simpler texts, move hide apps in settings)

### ISSUE THREAD

**Issue by drewski-00h** [falzonv/discreet-launcher#82]
Just an idea, but replacing the English (or French) text with icons (settings, folder, favorites) might clean up the menus.  In addition, it might be more universal to people who speak other languages, being a picture representation.  You could do a taller window (as it is now), or a wider window to accommodate the icons.

What do you think?

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!
I prefer to keep some texts for the menu entries, and inserting icons is not as straightforward as I thought due to the internal way the menu is created (the dialog takes a list of texts as parameter). Also tried with emojis but their appearance vary from one Android version to another and in some cases it doesn't look really good.

However, there is a proposal in PR #78 about simplifying the text menus.
If applied, it could give something like this:

| Current | Possible evolution |
| --- | --- |
| Manage favorites | Favorites
| Organize folders | Folders
| Hide applications | Hidden apps
| Refresh the applications list | Refresh the list of apps
| Settings / Help | Settings and help

What do you think about this?

Best regards.

**Comment by drewski-00h** [comment]
Yes, I do like the evolution better.  IMO, simpler is better.

Would you consider even removing the "Hidden Apps" part?  For me, it is the least used function of the app.  It's essential, but I only used it once the first time I set up the app.  It's entry would be in settings.

**Comment by falzonv** [comment]
Hello,

Ok, thank you for your feedback!
We will simplify the menu entries like this then :-)

You are right about the hidden apps entry, maybe it should be removed from this menu.
Except for development tests, I also never used it after the initial setup on my phone.
It may not be simple due to its internal code, but I will check how we could move this feature in the settings ;-)

Best regards.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that menu texts have been simplified as described above in new release v4.6.0!
This release has been published few minutes ago and should be available soon on stores.

Regarding the move of the hidden apps in the settings, it should be possible but a bit more complicated than I thought.
This is why it will be done in a next release (leaving this ticket opened for follow-up).

Best regards.

**Comment by falzonv** [comment]
Now in new version v4.7.0 the hidden apps button has been moved in the settings.
After it is published on F-Droid, I will close this ticket.

**Comment by falzonv** [comment]
Hello @drewski-00h,

Since v4.7.0 is now available on F-Droid, I will close this ticket.
Feel free to add comments if needed or wished.

I should also mention that, following new tests in ticket #110, I was finally able to add icons to menu entries by recreating a custom new dialog from scratch (see 1st screenshot).

Best regards.
