### ISSUE TITLE
Hide Search in App Drawer Option

### ISSUE THREAD

**Issue by n-ce** [falzonv/discreet-launcher#89]

**Comment by falzonv** [comment]
Hello,

The Search can already be hidden with the menu entry "Hide applications" (look for "Search" in the list).
Since it is also mentioned in the Help, I will close this ticket as solved.

Best regards.

**Comment by n-ce** [comment]
While Search is hiddenable, I can't seem to find a way to hide the discreet launcher icon itself in the drawer.

**Comment by falzonv** [comment]
Hello,

Indeed it is not possible to hide the launcher icon (it can be put in a folder, but not hidden).
This is because, if the option to hide the menu button is enabled, the only way to access the launcher menu (and all settings) is to use the launcher icon. If this icon is hidden, the user loses access to the menu.

Best regards.
