### ISSUE TITLE
add unread counter

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#9]
![unread](https://user-images.githubusercontent.com/67331785/111868278-c7ab8980-8957-11eb-9009-4bbb40a0e37e.png)

improve the launcher with unread counter

**Comment by falzonv** [comment]
Hello,

Ok noted, I will think about how to do it and keep you updated.

Best regards.

**Comment by falzonv** [comment]
Hello,

After trying several ideas, I am sorry but **I am not able to implement this feature in a satisfying way**.

To give a short summary:
- A way would be to "spy" the notification bar and update a counter for each application (when an application shows a notification we do +1, and when the user dismiss or open the notification we do -1) but this would give false results because all the notification would count, not only the unread messages. I also do not very like the idea.
*(Note: this is what the "Launcher3" stock application is doing to display a dot on icons, it tracks what happens in the notification bar and update the counts accordingly)*
- To really count only the unread messages, it seems needed to have permissions such as READ_SMS (in order to count the number of unread SMS) which is not good from a privacy point of view. It would probably also not work for mails or specific applications such as social networks which are not registered in the SMS database.

Maybe there are other ways but I was not able to find them, sorry this will not be done.

Best regards.
