### ISSUE TITLE
Hide, but find with search?

### ISSUE THREAD

**Issue by parabolapersuader** [falzonv/discreet-launcher#93]
It seems that once an app is hidden it won't show in the folders or the search either. I enjoy this with Nova Launcher: say I hide the media player. It should be launched by other apps, like the file manager. But in case I want to launch it, I search the apps and there it is.

Or maybe there should be two methods to hide apps: hide them for good (like it is today) and hide, but find them with search.

**Comment by falzonv** [comment]
Hello,

Thank you for your feedback!

Yes the feature to hide apps is intended to hide them everywhere in the launcher including search (this is mostly to manage some bloatware apps that cannot be disabled).

It is not planned to add a second list of hidden apps that should still be shown in the search. It would add a lot of complexity for a limited added value (if an app needs to be accessible, it is much more intuitive to simply not hide it).

Another solution, if you have several apps in this case, is to group them in a folder. That way, they are not directly visible anymore in the main list, but can still be found with the search.

Best regards.

**Comment by odanoburu** [comment]
Hey @falzonv, I can see why you wouldn't want to implement this, it certainly overlaps a lot with the functionality for hiding bloatware apps. The way I see it, showing the app on search only if you enter the full name would be a nice compromise, since you wouldn't ever input the name of the bloatware app. I can think of a few use cases for the hidden-but-findable feature:

- you live somewhere the police may force you to unlock your phone so they can check if you have any ‘undesirable’ apps like VPN apps (of course this assumes it's just a regular police stop, a special police force will easily find anything there is to find on your phone)
- you live somewhere where the possibility of a criminal forcing you to unlock your phone and transfer them money is not negligible (again, assuming a non-technically-minded mugger, a specialized criminal won't be fooled)
- you are a teenager and you have helicopter parents (or fanatic parents) and they don't want you to have simple apps like a messenger to talk to your friends outside school

Of course I understand if you still don't think it's worth it or if you don't have the time. Maybe I can look into it, although I don't know any Java. Anyway, thank you for this app, I'm enjoying it!

**Comment by falzonv** [comment]
Hello @odanoburu,

I am glad you like Discreet Launcer!

Thank you for the suggestion and examples.
However, I am not sure it would work that well:
- Finding the Discreet Launcher main menu entry "Hidden apps" is quite easy and it would provide the searcher with a direct summary of the "undesirable" apps if they were hidden (which may be incriminatory).
- If the app is used regularly, it would probably also appear in the Recent apps (because that's how Android works) and even non-technical people investigating for used apps would probably have a look there.

Although I didn't mentioned it in my previous comment, including in any way the hidden apps in the search results would also add a lot of code complexity and potential bugs due to how the internal lists are managed in Discreet Launcher.
Sorry this is not something I plan to implement.

However, I should mention that it is possible to rename an app from its long press menu.
It would apply only in Discreet Launcher of course (so still not in the Recent apps...) but could be an even better compromise as the app would be easily accessible (through an innocent name) while the list from "Hidden apps" would remain empty.
An icon pack may also be used, in case the app icon is so much recognizable that no plausible new name can be found.

I know that some messaging apps provide features to hide messages and conversations, maybe there is somewhere a VPN with features to hide itself under the form of another app such as a Calculator (really hypothetical, I have no idea if such app exist).

Best regards.

**Comment by odanoburu** [comment]
ok, thanks, I understand!

> I know that some messaging apps provide features to hide messages and conversations, maybe there is somewhere a VPN with features to hide itself under the form of another app such as a Calculator (really hypothetical, I have no idea if such app exist).

in this spirit I think it makes sense to leave this to specialized software, this launcher is not a security app!
