### ISSUE TITLE
Home screen only

### ISSUE THREAD

**Issue by Pantyhose-X** [falzonv/discreet-launcher#94]
Home screen only
* All your apps will be shown on the Home screen.
* Show all apps on home screen
![Screenshot_20210427-093745](https://user-images.githubusercontent.com/42504385/116172999-df004280-a75f-11eb-8048-50c44f2308ca.jpg)

**Comment by falzonv** [comment]
Hello,

Sorry, I do not plan to implement this because the idea of this launcher is to have en empty home screen.

However, you may be interested by Keikai Launcher (https://f-droid.org/en/packages/com.anpmech.launcher/) which displays all the apps directly on the home screen like you suggested.

Best regards.

**Comment by n-ce** [comment]
> Home screen only
> 
> * All your apps will be shown on the Home screen.
> * Show all apps on home screen
>   ![Screenshot_20210427-093745](https://user-images.githubusercontent.com/42504385/116172999-df004280-a75f-11eb-8048-50c44f2308ca.jpg)

Its possible to turn Discreet to Homescreen only.
Setup - 
- choose All apps on favorites (after #100 limit will be removed)
- Turn off App Drawer
- Set Favorites to always show
