### ISSUE TITLE
emoji never work - no padding on notification

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#99]
![1](https://user-images.githubusercontent.com/67331785/126867608-c132e54e-399b-4ec3-887b-ac515b0b720b.png)
![2](https://user-images.githubusercontent.com/67331785/126867616-e025663f-4349-4cc5-994a-0ea80a57e260.png)
![3](https://user-images.githubusercontent.com/67331785/126867626-8da4068c-34e9-498c-be17-632dac057a4d.png)

**Comment by falzonv** [comment]
Hello,

Thank you for the bug report.
It is strange because, as usual, I don't have these display bugs even with the Android 5 emulator...

For the emojis I used the same way which was working on your phone in #86, and now it doesn't work anymore :-/
=> I will remove the emojis, it seems to cause too many problems with some devices (probably due to encoding).

Here is another version of the APK without the emojis if you want to test:
https://file.re/2021/07/24/discreet-launcher-v460no-emoji/

---

For the notification it is very weird because we only simplified the text in #78.
Nothing was changed about the padding and margins so I really don't understand why they disappeared on your side.
Did you already observed these margins problem with v4.5.0?

Here is how it looks on my Android 5 emulator:
![2021-07-24_notification_android5](https://user-images.githubusercontent.com/4698531/126869727-a4f1e5aa-63c8-4fd3-bdc4-9ed7fb4de27d.jpg)

Best regards.

**Comment by xi7** [comment]
name show normal now. 

about notification why u no check that app i send before, it can choose color and work with android 5 very good without strange space bar.

**Comment by falzonv** [comment]
Ok thank you for confirmation for the names, I will publish a v4.6.1 to apply this.

---

> why u no check that app i send before

I tried but was not able to find its source code, this app doesn't seem to be open source.

Regarding my previous question, did you also observed these margins problem with v4.5.0?

**Comment by xi7** [comment]
4.5.0 and 4.6.1 solved margins

**Comment by xi7** [comment]
limit while only icons favorites can be increase.

**Comment by falzonv** [comment]
> limit while only icons favorites can be increase.

Thank you for the suggestion, created ticket #100 for follow-up.

**Comment by falzonv** [comment]
I will close this ticket since v4.6.1 is now available on F-Droid (v4.6.0 was skipped).
